module spectral_output

   use shr_kind_mod,     only: r8 => shr_kind_r8
   use radgrid,          only: ntot_wavlnrng
   use ppgrid

   implicit none
   private 
   save

!
! Pubic Interfaces
!
  public :: addfld_spectral_intervals
  public :: outfld_spectral_flux_fullsky
  public :: outfld_spectral_flux_clearsky

!============================================================================
contains
!============================================================================

!============================================================================
!
! Public subroutines
!
!============================================================================


!============================================================================
 
  subroutine addfld_spectral_intervals

!------------------------------------------------------------------------
!
! Purpose:  Add spectral output to master field list
!
!------------------------------------------------------------------------
!
    use cam_history,     only: addfld, phys_decomp

    ! shortwave fieldsa
    call addfld ('FUS_int01     ','W/m2    ',pverp,'A','Shortwave upward flux, spectral interval 01',phys_decomp)
    call addfld ('FDS_int01     ','W/m2    ',pverp,'A','Shortwave downward flux, spectral interval 01',phys_decomp)
    call addfld ('FUSC_int01     ','W/m2    ',pverp,'A','Shortwave clear-sky upward flux, spectral interval 01',phys_decomp)
    call addfld ('FDSC_int01     ','W/m2    ',pverp,'A','Shortwave clear-sky downward flux, spectral interval 01',phys_decomp)
    call addfld ('FUS_toa_int01     ','W/m2    ',1,'A','Shortwave upward flux, spectral interval 01, toa',phys_decomp)
    call addfld ('FDS_toa_int01     ','W/m2    ',1,'A','Shortwave downward flux, spectral interval 01, toa',phys_decomp)
    call addfld ('FUSC_toa_int01     ','W/m2    ',1,'A','Shortwave clear-sky upward flux, spectral interval 01, toa',phys_decomp)
    call addfld ('FDSC_toa_int01     ','W/m2    ',1,'A','Shortwave clear-sky downward flux, spectral interval 01, toa',phys_decomp)

    call addfld ('FUS_int02     ','W/m2    ',pverp,'A','Shortwave upward flux, spectral interval 02',phys_decomp)
    call addfld ('FDS_int02     ','W/m2    ',pverp,'A','Shortwave downward flux, spectral interval 02',phys_decomp)
    call addfld ('FUSC_int02     ','W/m2    ',pverp,'A','Shortwave clear-sky upward flux, spectral interval 02',phys_decomp)
    call addfld ('FDSC_int02     ','W/m2    ',pverp,'A','Shortwave clear-sky downward flux, spectral interval 02',phys_decomp)
    call addfld ('FUS_toa_int02     ','W/m2    ',1,'A','Shortwave upward flux, spectral interval 02, toa',phys_decomp)
    call addfld ('FDS_toa_int02     ','W/m2    ',1,'A','Shortwave downward flux, spectral interval 02, toa',phys_decomp)
    call addfld ('FUSC_toa_int02     ','W/m2    ',1,'A','Shortwave clear-sky upward flux, spectral interval 02, toa',phys_decomp)
    call addfld ('FDSC_toa_int02     ','W/m2    ',1,'A','Shortwave clear-sky downward flux, spectral interval 02, toa',phys_decomp)

    call addfld ('FUS_int03     ','W/m2    ',pverp,'A','Shortwave upward flux, spectral interval 03',phys_decomp)
    call addfld ('FDS_int03     ','W/m2    ',pverp,'A','Shortwave downward flux, spectral interval 03',phys_decomp)
    call addfld ('FUSC_int03     ','W/m2    ',pverp,'A','Shortwave clear-sky upward flux, spectral interval 03',phys_decomp)
    call addfld ('FDSC_int03     ','W/m2    ',pverp,'A','Shortwave clear-sky downward flux, spectral interval 03',phys_decomp)
    call addfld ('FUS_toa_int03     ','W/m2    ',1,'A','Shortwave upward flux, spectral interval 03, toa',phys_decomp)
    call addfld ('FDS_toa_int03     ','W/m2    ',1,'A','Shortwave downward flux, spectral interval 03, toa',phys_decomp)
    call addfld ('FUSC_toa_int03     ','W/m2    ',1,'A','Shortwave clear-sky upward flux, spectral interval 03, toa',phys_decomp)
    call addfld ('FDSC_toa_int03     ','W/m2    ',1,'A','Shortwave clear-sky downward flux, spectral interval 03, toa',phys_decomp)

    call addfld ('FUS_int04     ','W/m2    ',pverp,'A','Shortwave upward flux, spectral interval 04',phys_decomp)
    call addfld ('FDS_int04     ','W/m2    ',pverp,'A','Shortwave downward flux, spectral interval 04',phys_decomp)
    call addfld ('FUSC_int04     ','W/m2    ',pverp,'A','Shortwave clear-sky upward flux, spectral interval 04',phys_decomp)
    call addfld ('FDSC_int04     ','W/m2    ',pverp,'A','Shortwave clear-sky downward flux, spectral interval 04',phys_decomp)
    call addfld ('FUS_toa_int04     ','W/m2    ',1,'A','Shortwave upward flux, spectral interval 04, toa',phys_decomp)
    call addfld ('FDS_toa_int04     ','W/m2    ',1,'A','Shortwave downward flux, spectral interval 04, toa',phys_decomp)
    call addfld ('FUSC_toa_int04     ','W/m2    ',1,'A','Shortwave clear-sky upward flux, spectral interval 04, toa',phys_decomp)
    call addfld ('FDSC_toa_int04     ','W/m2    ',1,'A','Shortwave clear-sky downward flux, spectral interval 04, toa',phys_decomp)

    call addfld ('FUS_int05     ','W/m2    ',pverp,'A','Shortwave upward flux, spectral interval 05',phys_decomp)
    call addfld ('FDS_int05     ','W/m2    ',pverp,'A','Shortwave downward flux, spectral interval 05',phys_decomp)
    call addfld ('FUSC_int05     ','W/m2    ',pverp,'A','Shortwave clear-sky upward flux, spectral interval 05',phys_decomp)
    call addfld ('FDSC_int05     ','W/m2    ',pverp,'A','Shortwave clear-sky downward flux, spectral interval 05',phys_decomp)
    call addfld ('FUS_toa_int05     ','W/m2    ',1,'A','Shortwave upward flux, spectral interval 05, toa',phys_decomp)
    call addfld ('FDS_toa_int05     ','W/m2    ',1,'A','Shortwave downward flux, spectral interval 05, toa',phys_decomp)
    call addfld ('FUSC_toa_int05     ','W/m2    ',1,'A','Shortwave clear-sky upward flux, spectral interval 05, toa',phys_decomp)
    call addfld ('FDSC_toa_int05     ','W/m2    ',1,'A','Shortwave clear-sky downward flux, spectral interval 05, toa',phys_decomp)

    call addfld ('FUS_int06     ','W/m2    ',pverp,'A','Shortwave upward flux, spectral interval 06',phys_decomp)
    call addfld ('FDS_int06     ','W/m2    ',pverp,'A','Shortwave downward flux, spectral interval 06',phys_decomp)
    call addfld ('FUSC_int06     ','W/m2    ',pverp,'A','Shortwave clear-sky upward flux, spectral interval 06',phys_decomp)
    call addfld ('FDSC_int06     ','W/m2    ',pverp,'A','Shortwave clear-sky downward flux, spectral interval 06',phys_decomp)
    call addfld ('FUS_toa_int06     ','W/m2    ',1,'A','Shortwave upward flux, spectral interval 06, toa',phys_decomp)
    call addfld ('FDS_toa_int06     ','W/m2    ',1,'A','Shortwave downward flux, spectral interval 06, toa',phys_decomp)
    call addfld ('FUSC_toa_int06     ','W/m2    ',1,'A','Shortwave clear-sky upward flux, spectral interval 06, toa',phys_decomp)
    call addfld ('FDSC_toa_int06     ','W/m2    ',1,'A','Shortwave clear-sky downward flux, spectral interval 06, toa',phys_decomp)

    call addfld ('FUS_int07     ','W/m2    ',pverp,'A','Shortwave upward flux, spectral interval 07',phys_decomp)
    call addfld ('FDS_int07     ','W/m2    ',pverp,'A','Shortwave downward flux, spectral interval 07',phys_decomp)
    call addfld ('FUSC_int07     ','W/m2    ',pverp,'A','Shortwave clear-sky upward flux, spectral interval 07',phys_decomp)
    call addfld ('FDSC_int07     ','W/m2    ',pverp,'A','Shortwave clear-sky downward flux, spectral interval 07',phys_decomp)
    call addfld ('FUS_toa_int07     ','W/m2    ',1,'A','Shortwave upward flux, spectral interval 07, toa',phys_decomp)
    call addfld ('FDS_toa_int07     ','W/m2    ',1,'A','Shortwave downward flux, spectral interval 07, toa',phys_decomp)
    call addfld ('FUSC_toa_int07     ','W/m2    ',1,'A','Shortwave clear-sky upward flux, spectral interval 07, toa',phys_decomp)
    call addfld ('FDSC_toa_int07     ','W/m2    ',1,'A','Shortwave clear-sky downward flux, spectral interval 07, toa',phys_decomp)

    call addfld ('FUS_int08     ','W/m2    ',pverp,'A','Shortwave upward flux, spectral interval 08',phys_decomp)
    call addfld ('FDS_int08     ','W/m2    ',pverp,'A','Shortwave downward flux, spectral interval 08',phys_decomp)
    call addfld ('FUSC_int08     ','W/m2    ',pverp,'A','Shortwave clear-sky upward flux, spectral interval 08',phys_decomp)
    call addfld ('FDSC_int08     ','W/m2    ',pverp,'A','Shortwave clear-sky downward flux, spectral interval 08',phys_decomp)
    call addfld ('FUS_toa_int08     ','W/m2    ',1,'A','Shortwave upward flux, spectral interval 08, toa',phys_decomp)
    call addfld ('FDS_toa_int08     ','W/m2    ',1,'A','Shortwave downward flux, spectral interval 08, toa',phys_decomp)
    call addfld ('FUSC_toa_int08     ','W/m2    ',1,'A','Shortwave clear-sky upward flux, spectral interval 08, toa',phys_decomp)
    call addfld ('FDSC_toa_int08     ','W/m2    ',1,'A','Shortwave clear-sky downward flux, spectral interval 08, toa',phys_decomp)

    call addfld ('FUS_int09     ','W/m2    ',pverp,'A','Shortwave upward flux, spectral interval 09',phys_decomp)
    call addfld ('FDS_int09     ','W/m2    ',pverp,'A','Shortwave downward flux, spectral interval 09',phys_decomp)
    call addfld ('FUSC_int09     ','W/m2    ',pverp,'A','Shortwave clear-sky upward flux, spectral interval 09',phys_decomp)
    call addfld ('FDSC_int09     ','W/m2    ',pverp,'A','Shortwave clear-sky downward flux, spectral interval 09',phys_decomp)
    call addfld ('FUS_toa_int09     ','W/m2    ',1,'A','Shortwave upward flux, spectral interval 09, toa',phys_decomp)
    call addfld ('FDS_toa_int09     ','W/m2    ',1,'A','Shortwave downward flux, spectral interval 09, toa',phys_decomp)
    call addfld ('FUSC_toa_int09     ','W/m2    ',1,'A','Shortwave clear-sky upward flux, spectral interval 09, toa',phys_decomp)
    call addfld ('FDSC_toa_int09     ','W/m2    ',1,'A','Shortwave clear-sky downward flux, spectral interval 09, toa',phys_decomp)

    call addfld ('FUS_int10     ','W/m2    ',pverp,'A','Shortwave upward flux, spectral interval 10',phys_decomp)
    call addfld ('FDS_int10     ','W/m2    ',pverp,'A','Shortwave downward flux, spectral interval 10',phys_decomp)
    call addfld ('FUSC_int10     ','W/m2    ',pverp,'A','Shortwave clear-sky upward flux, spectral interval 10',phys_decomp)
    call addfld ('FDSC_int10     ','W/m2    ',pverp,'A','Shortwave clear-sky downward flux, spectral interval 10',phys_decomp)
    call addfld ('FUS_toa_int10     ','W/m2    ',1,'A','Shortwave upward flux, spectral interval 10, toa',phys_decomp)
    call addfld ('FDS_toa_int10     ','W/m2    ',1,'A','Shortwave downward flux, spectral interval 10, toa',phys_decomp)
    call addfld ('FUSC_toa_int10     ','W/m2    ',1,'A','Shortwave clear-sky upward flux, spectral interval 10, toa',phys_decomp)
    call addfld ('FDSC_toa_int10     ','W/m2    ',1,'A','Shortwave clear-sky downward flux, spectral interval 10, toa',phys_decomp)

    call addfld ('FUS_int11     ','W/m2    ',pverp,'A','Shortwave upward flux, spectral interval 11',phys_decomp)
    call addfld ('FDS_int11     ','W/m2    ',pverp,'A','Shortwave downward flux, spectral interval 11',phys_decomp)
    call addfld ('FUSC_int11     ','W/m2    ',pverp,'A','Shortwave clear-sky upward flux, spectral interval 11',phys_decomp)
    call addfld ('FDSC_int11     ','W/m2    ',pverp,'A','Shortwave clear-sky downward flux, spectral interval 11',phys_decomp)
    call addfld ('FUS_toa_int11     ','W/m2    ',1,'A','Shortwave upward flux, spectral interval 11, toa',phys_decomp)
    call addfld ('FDS_toa_int11     ','W/m2    ',1,'A','Shortwave downward flux, spectral interval 11, toa',phys_decomp)
    call addfld ('FUSC_toa_int11     ','W/m2    ',1,'A','Shortwave clear-sky upward flux, spectral interval 11, toa',phys_decomp)
    call addfld ('FDSC_toa_int11     ','W/m2    ',1,'A','Shortwave clear-sky downward flux, spectral interval 11, toa',phys_decomp)

    call addfld ('FUS_int12     ','W/m2    ',pverp,'A','Shortwave upward flux, spectral interval 12',phys_decomp)
    call addfld ('FDS_int12     ','W/m2    ',pverp,'A','Shortwave downward flux, spectral interval 12',phys_decomp)
    call addfld ('FUSC_int12     ','W/m2    ',pverp,'A','Shortwave clear-sky upward flux, spectral interval 12',phys_decomp)
    call addfld ('FDSC_int12     ','W/m2    ',pverp,'A','Shortwave clear-sky downward flux, spectral interval 12',phys_decomp)
    call addfld ('FUS_toa_int12     ','W/m2    ',1,'A','Shortwave upward flux, spectral interval 12, toa',phys_decomp)
    call addfld ('FDS_toa_int12     ','W/m2    ',1,'A','Shortwave downward flux, spectral interval 12, toa',phys_decomp)
    call addfld ('FUSC_toa_int12     ','W/m2    ',1,'A','Shortwave clear-sky upward flux, spectral interval 12, toa',phys_decomp)
    call addfld ('FDSC_toa_int12     ','W/m2    ',1,'A','Shortwave clear-sky downward flux, spectral interval 12, toa',phys_decomp)

    call addfld ('FUS_int13     ','W/m2    ',pverp,'A','Shortwave upward flux, spectral interval 13',phys_decomp)
    call addfld ('FDS_int13     ','W/m2    ',pverp,'A','Shortwave downward flux, spectral interval 13',phys_decomp)
    call addfld ('FUSC_int13     ','W/m2    ',pverp,'A','Shortwave clear-sky upward flux, spectral interval 13',phys_decomp)
    call addfld ('FDSC_int13     ','W/m2    ',pverp,'A','Shortwave clear-sky downward flux, spectral interval 13',phys_decomp)
    call addfld ('FUS_toa_int13     ','W/m2    ',1,'A','Shortwave upward flux, spectral interval 13, toa',phys_decomp)
    call addfld ('FDS_toa_int13     ','W/m2    ',1,'A','Shortwave downward flux, spectral interval 13, toa',phys_decomp)
    call addfld ('FUSC_toa_int13     ','W/m2    ',1,'A','Shortwave clear-sky upward flux, spectral interval 13, toa',phys_decomp)
    call addfld ('FDSC_toa_int13     ','W/m2    ',1,'A','Shortwave clear-sky downward flux, spectral interval 13, toa',phys_decomp)

    call addfld ('FUS_int14     ','W/m2    ',pverp,'A','Shortwave upward flux, spectral interval 14',phys_decomp)
    call addfld ('FDS_int14     ','W/m2    ',pverp,'A','Shortwave downward flux, spectral interval 14',phys_decomp)
    call addfld ('FUSC_int14     ','W/m2    ',pverp,'A','Shortwave clear-sky upward flux, spectral interval 14',phys_decomp)
    call addfld ('FDSC_int14     ','W/m2    ',pverp,'A','Shortwave clear-sky downward flux, spectral interval 14',phys_decomp)
    call addfld ('FUS_toa_int14     ','W/m2    ',1,'A','Shortwave upward flux, spectral interval 14, toa',phys_decomp)
    call addfld ('FDS_toa_int14     ','W/m2    ',1,'A','Shortwave downward flux, spectral interval 14, toa',phys_decomp)
    call addfld ('FUSC_toa_int14     ','W/m2    ',1,'A','Shortwave clear-sky upward flux, spectral interval 14, toa',phys_decomp)
    call addfld ('FDSC_toa_int14     ','W/m2    ',1,'A','Shortwave clear-sky downward flux, spectral interval 14, toa',phys_decomp)

    call addfld ('FUS_int15     ','W/m2    ',pverp,'A','Shortwave upward flux, spectral interval 15',phys_decomp)
    call addfld ('FDS_int15     ','W/m2    ',pverp,'A','Shortwave downward flux, spectral interval 15',phys_decomp)
    call addfld ('FUSC_int15     ','W/m2    ',pverp,'A','Shortwave clear-sky upward flux, spectral interval 15',phys_decomp)
    call addfld ('FDSC_int15     ','W/m2    ',pverp,'A','Shortwave clear-sky downward flux, spectral interval 15',phys_decomp)
    call addfld ('FUS_toa_int15     ','W/m2    ',1,'A','Shortwave upward flux, spectral interval 15, toa',phys_decomp)
    call addfld ('FDS_toa_int15     ','W/m2    ',1,'A','Shortwave downward flux, spectral interval 15, toa',phys_decomp)
    call addfld ('FUSC_toa_int15     ','W/m2    ',1,'A','Shortwave clear-sky upward flux, spectral interval 15, toa',phys_decomp)
    call addfld ('FDSC_toa_int15     ','W/m2    ',1,'A','Shortwave clear-sky downward flux, spectral interval 15, toa',phys_decomp)

    call addfld ('FUS_int16     ','W/m2    ',pverp,'A','Shortwave upward flux, spectral interval 16',phys_decomp)
    call addfld ('FDS_int16     ','W/m2    ',pverp,'A','Shortwave downward flux, spectral interval 16',phys_decomp)
    call addfld ('FUSC_int16     ','W/m2    ',pverp,'A','Shortwave clear-sky upward flux, spectral interval 16',phys_decomp)
    call addfld ('FDSC_int16     ','W/m2    ',pverp,'A','Shortwave clear-sky downward flux, spectral interval 16',phys_decomp)
    call addfld ('FUS_toa_int16     ','W/m2    ',1,'A','Shortwave upward flux, spectral interval 16, toa',phys_decomp)
    call addfld ('FDS_toa_int16     ','W/m2    ',1,'A','Shortwave downward flux, spectral interval 16, toa',phys_decomp)
    call addfld ('FUSC_toa_int16     ','W/m2    ',1,'A','Shortwave clear-sky upward flux, spectral interval 16, toa',phys_decomp)
    call addfld ('FDSC_toa_int16     ','W/m2    ',1,'A','Shortwave clear-sky downward flux, spectral interval 16, toa',phys_decomp)

    call addfld ('FUS_int17     ','W/m2    ',pverp,'A','Shortwave upward flux, spectral interval 17',phys_decomp)
    call addfld ('FDS_int17     ','W/m2    ',pverp,'A','Shortwave downward flux, spectral interval 17',phys_decomp)
    call addfld ('FUSC_int17     ','W/m2    ',pverp,'A','Shortwave clear-sky upward flux, spectral interval 17',phys_decomp)
    call addfld ('FDSC_int17     ','W/m2    ',pverp,'A','Shortwave clear-sky downward flux, spectral interval 17',phys_decomp)
    call addfld ('FUS_toa_int17     ','W/m2    ',1,'A','Shortwave upward flux, spectral interval 17, toa',phys_decomp)
    call addfld ('FDS_toa_int17     ','W/m2    ',1,'A','Shortwave downward flux, spectral interval 17, toa',phys_decomp)
    call addfld ('FUSC_toa_int17     ','W/m2    ',1,'A','Shortwave clear-sky upward flux, spectral interval 17, toa',phys_decomp)
    call addfld ('FDSC_toa_int17     ','W/m2    ',1,'A','Shortwave clear-sky downward flux, spectral interval 17, toa',phys_decomp)

    call addfld ('FUS_int18     ','W/m2    ',pverp,'A','Shortwave upward flux, spectral interval 18',phys_decomp)
    call addfld ('FDS_int18     ','W/m2    ',pverp,'A','Shortwave downward flux, spectral interval 18',phys_decomp)
    call addfld ('FUSC_int18     ','W/m2    ',pverp,'A','Shortwave clear-sky upward flux, spectral interval 18',phys_decomp)
    call addfld ('FDSC_int18     ','W/m2    ',pverp,'A','Shortwave clear-sky downward flux, spectral interval 18',phys_decomp)
    call addfld ('FUS_toa_int18     ','W/m2    ',1,'A','Shortwave upward flux, spectral interval 18, toa',phys_decomp)
    call addfld ('FDS_toa_int18     ','W/m2    ',1,'A','Shortwave downward flux, spectral interval 18, toa',phys_decomp)
    call addfld ('FUSC_toa_int18     ','W/m2    ',1,'A','Shortwave clear-sky upward flux, spectral interval 18, toa',phys_decomp)
    call addfld ('FDSC_toa_int18     ','W/m2    ',1,'A','Shortwave clear-sky downward flux, spectral interval 18, toa',phys_decomp)

    call addfld ('FUS_int19     ','W/m2    ',pverp,'A','Shortwave upward flux, spectral interval 19',phys_decomp)
    call addfld ('FDS_int19     ','W/m2    ',pverp,'A','Shortwave downward flux, spectral interval 19',phys_decomp)
    call addfld ('FUSC_int19     ','W/m2    ',pverp,'A','Shortwave clear-sky upward flux, spectral interval 19',phys_decomp)
    call addfld ('FDSC_int19     ','W/m2    ',pverp,'A','Shortwave clear-sky downward flux, spectral interval 19',phys_decomp)
    call addfld ('FUS_toa_int19     ','W/m2    ',1,'A','Shortwave upward flux, spectral interval 19, toa',phys_decomp)
    call addfld ('FDS_toa_int19     ','W/m2    ',1,'A','Shortwave downward flux, spectral interval 19, toa',phys_decomp)
    call addfld ('FUSC_toa_int19     ','W/m2    ',1,'A','Shortwave clear-sky upward flux, spectral interval 19, toa',phys_decomp)
    call addfld ('FDSC_toa_int19     ','W/m2    ',1,'A','Shortwave clear-sky downward flux, spectral interval 19, toa',phys_decomp)

    call addfld ('FUS_int20     ','W/m2    ',pverp,'A','Shortwave upward flux, spectral interval 20',phys_decomp)
    call addfld ('FDS_int20     ','W/m2    ',pverp,'A','Shortwave downward flux, spectral interval 20',phys_decomp)
    call addfld ('FUSC_int20     ','W/m2    ',pverp,'A','Shortwave clear-sky upward flux, spectral interval 20',phys_decomp)
    call addfld ('FDSC_int20     ','W/m2    ',pverp,'A','Shortwave clear-sky downward flux, spectral interval 20',phys_decomp)
    call addfld ('FUS_toa_int20     ','W/m2    ',1,'A','Shortwave upward flux, spectral interval 20, toa',phys_decomp)
    call addfld ('FDS_toa_int20     ','W/m2    ',1,'A','Shortwave downward flux, spectral interval 20, toa',phys_decomp)
    call addfld ('FUSC_toa_int20     ','W/m2    ',1,'A','Shortwave clear-sky upward flux, spectral interval 20, toa',phys_decomp)
    call addfld ('FDSC_toa_int20     ','W/m2    ',1,'A','Shortwave clear-sky downward flux, spectral interval 20, toa',phys_decomp)

    call addfld ('FUS_int21     ','W/m2    ',pverp,'A','Shortwave upward flux, spectral interval 21',phys_decomp)
    call addfld ('FDS_int21     ','W/m2    ',pverp,'A','Shortwave downward flux, spectral interval 21',phys_decomp)
    call addfld ('FUSC_int21     ','W/m2    ',pverp,'A','Shortwave clear-sky upward flux, spectral interval 21',phys_decomp)
    call addfld ('FDSC_int21     ','W/m2    ',pverp,'A','Shortwave clear-sky downward flux, spectral interval 21',phys_decomp)
    call addfld ('FUS_toa_int21     ','W/m2    ',1,'A','Shortwave upward flux, spectral interval 21, toa',phys_decomp)
    call addfld ('FDS_toa_int21     ','W/m2    ',1,'A','Shortwave downward flux, spectral interval 21, toa',phys_decomp)
    call addfld ('FUSC_toa_int21     ','W/m2    ',1,'A','Shortwave clear-sky upward flux, spectral interval 21, toa',phys_decomp)
    call addfld ('FDSC_toa_int21     ','W/m2    ',1,'A','Shortwave clear-sky downward flux, spectral interval 21, toa',phys_decomp)

    call addfld ('FUS_int22     ','W/m2    ',pverp,'A','Shortwave upward flux, spectral interval 22',phys_decomp)
    call addfld ('FDS_int22     ','W/m2    ',pverp,'A','Shortwave downward flux, spectral interval 22',phys_decomp)
    call addfld ('FUSC_int22     ','W/m2    ',pverp,'A','Shortwave clear-sky upward flux, spectral interval 22',phys_decomp)
    call addfld ('FDSC_int22     ','W/m2    ',pverp,'A','Shortwave clear-sky downward flux, spectral interval 22',phys_decomp)
    call addfld ('FUS_toa_int22     ','W/m2    ',1,'A','Shortwave upward flux, spectral interval 22, toa',phys_decomp)
    call addfld ('FDS_toa_int22     ','W/m2    ',1,'A','Shortwave downward flux, spectral interval 22, toa',phys_decomp)
    call addfld ('FUSC_toa_int22     ','W/m2    ',1,'A','Shortwave clear-sky upward flux, spectral interval 22, toa',phys_decomp)
    call addfld ('FDSC_toa_int22     ','W/m2    ',1,'A','Shortwave clear-sky downward flux, spectral interval 22, toa',phys_decomp)

    call addfld ('FUS_int23     ','W/m2    ',pverp,'A','Shortwave upward flux, spectral interval 23',phys_decomp)
    call addfld ('FDS_int23     ','W/m2    ',pverp,'A','Shortwave downward flux, spectral interval 23',phys_decomp)
    call addfld ('FUSC_int23     ','W/m2    ',pverp,'A','Shortwave clear-sky upward flux, spectral interval 23',phys_decomp)
    call addfld ('FDSC_int23     ','W/m2    ',pverp,'A','Shortwave clear-sky downward flux, spectral interval 23',phys_decomp)
    call addfld ('FUS_toa_int23     ','W/m2    ',1,'A','Shortwave upward flux, spectral interval 23, toa',phys_decomp)
    call addfld ('FDS_toa_int23     ','W/m2    ',1,'A','Shortwave downward flux, spectral interval 23, toa',phys_decomp)
    call addfld ('FUSC_toa_int23     ','W/m2    ',1,'A','Shortwave clear-sky upward flux, spectral interval 23, toa',phys_decomp)
    call addfld ('FDSC_toa_int23     ','W/m2    ',1,'A','Shortwave clear-sky downward flux, spectral interval 23, toa',phys_decomp)

    call addfld ('FUS_int24     ','W/m2    ',pverp,'A','Shortwave upward flux, spectral interval 24',phys_decomp)
    call addfld ('FDS_int24     ','W/m2    ',pverp,'A','Shortwave downward flux, spectral interval 24',phys_decomp)
    call addfld ('FUSC_int24     ','W/m2    ',pverp,'A','Shortwave clear-sky upward flux, spectral interval 24',phys_decomp)
    call addfld ('FDSC_int24     ','W/m2    ',pverp,'A','Shortwave clear-sky downward flux, spectral interval 24',phys_decomp)
    call addfld ('FUS_toa_int24     ','W/m2    ',1,'A','Shortwave upward flux, spectral interval 24, toa',phys_decomp)
    call addfld ('FDS_toa_int24     ','W/m2    ',1,'A','Shortwave downward flux, spectral interval 24, toa',phys_decomp)
    call addfld ('FUSC_toa_int24     ','W/m2    ',1,'A','Shortwave clear-sky upward flux, spectral interval 24, toa',phys_decomp)
    call addfld ('FDSC_toa_int24     ','W/m2    ',1,'A','Shortwave clear-sky downward flux, spectral interval 24, toa',phys_decomp)

    call addfld ('FUS_int25     ','W/m2    ',pverp,'A','Shortwave upward flux, spectral interval 25',phys_decomp)
    call addfld ('FDS_int25     ','W/m2    ',pverp,'A','Shortwave downward flux, spectral interval 25',phys_decomp)
    call addfld ('FUSC_int25     ','W/m2    ',pverp,'A','Shortwave clear-sky upward flux, spectral interval 25',phys_decomp)
    call addfld ('FDSC_int25     ','W/m2    ',pverp,'A','Shortwave clear-sky downward flux, spectral interval 25',phys_decomp)
    call addfld ('FUS_toa_int25     ','W/m2    ',1,'A','Shortwave upward flux, spectral interval 25, toa',phys_decomp)
    call addfld ('FDS_toa_int25     ','W/m2    ',1,'A','Shortwave downward flux, spectral interval 25, toa',phys_decomp)
    call addfld ('FUSC_toa_int25     ','W/m2    ',1,'A','Shortwave clear-sky upward flux, spectral interval 25, toa',phys_decomp)
    call addfld ('FDSC_toa_int25     ','W/m2    ',1,'A','Shortwave clear-sky downward flux, spectral interval 25, toa',phys_decomp)

    call addfld ('FUS_int26     ','W/m2    ',pverp,'A','Shortwave upward flux, spectral interval 26',phys_decomp)
    call addfld ('FDS_int26     ','W/m2    ',pverp,'A','Shortwave downward flux, spectral interval 26',phys_decomp)
    call addfld ('FUSC_int26     ','W/m2    ',pverp,'A','Shortwave clear-sky upward flux, spectral interval 26',phys_decomp)
    call addfld ('FDSC_int26     ','W/m2    ',pverp,'A','Shortwave clear-sky downward flux, spectral interval 26',phys_decomp)
    call addfld ('FUS_toa_int26     ','W/m2    ',1,'A','Shortwave upward flux, spectral interval 26, toa',phys_decomp)
    call addfld ('FDS_toa_int26     ','W/m2    ',1,'A','Shortwave downward flux, spectral interval 26, toa',phys_decomp)
    call addfld ('FUSC_toa_int26     ','W/m2    ',1,'A','Shortwave clear-sky upward flux, spectral interval 26, toa',phys_decomp)
    call addfld ('FDSC_toa_int26     ','W/m2    ',1,'A','Shortwave clear-sky downward flux, spectral interval 26, toa',phys_decomp)

    call addfld ('FUS_int27     ','W/m2    ',pverp,'A','Shortwave upward flux, spectral interval 27',phys_decomp)
    call addfld ('FDS_int27     ','W/m2    ',pverp,'A','Shortwave downward flux, spectral interval 27',phys_decomp)
    call addfld ('FUSC_int27     ','W/m2    ',pverp,'A','Shortwave clear-sky upward flux, spectral interval 27',phys_decomp)
    call addfld ('FDSC_int27     ','W/m2    ',pverp,'A','Shortwave clear-sky downward flux, spectral interval 27',phys_decomp)
    call addfld ('FUS_toa_int27     ','W/m2    ',1,'A','Shortwave upward flux, spectral interval 27, toa',phys_decomp)
    call addfld ('FDS_toa_int27     ','W/m2    ',1,'A','Shortwave downward flux, spectral interval 27, toa',phys_decomp)
    call addfld ('FUSC_toa_int27     ','W/m2    ',1,'A','Shortwave clear-sky upward flux, spectral interval 27, toa',phys_decomp)
    call addfld ('FDSC_toa_int27     ','W/m2    ',1,'A','Shortwave clear-sky downward flux, spectral interval 27, toa',phys_decomp)

    call addfld ('FUS_int28     ','W/m2    ',pverp,'A','Shortwave upward flux, spectral interval 28',phys_decomp)
    call addfld ('FDS_int28     ','W/m2    ',pverp,'A','Shortwave downward flux, spectral interval 28',phys_decomp)
    call addfld ('FUSC_int28     ','W/m2    ',pverp,'A','Shortwave clear-sky upward flux, spectral interval 28',phys_decomp)
    call addfld ('FDSC_int28     ','W/m2    ',pverp,'A','Shortwave clear-sky downward flux, spectral interval 28',phys_decomp)
    call addfld ('FUS_toa_int28     ','W/m2    ',1,'A','Shortwave upward flux, spectral interval 28, toa',phys_decomp)
    call addfld ('FDS_toa_int28     ','W/m2    ',1,'A','Shortwave downward flux, spectral interval 28, toa',phys_decomp)
    call addfld ('FUSC_toa_int28     ','W/m2    ',1,'A','Shortwave clear-sky upward flux, spectral interval 28, toa',phys_decomp)
    call addfld ('FDSC_toa_int28     ','W/m2    ',1,'A','Shortwave clear-sky downward flux, spectral interval 28, toa',phys_decomp)
 
    ! long wave fields
    call addfld ('FUL_int01     ','W/m2    ',pverp,'A','Longwave upward flux, spectral interval 01',phys_decomp)
    call addfld ('FDL_int01     ','W/m2    ',pverp,'A','Longwave downward flux, spectral interval 01',phys_decomp)
    call addfld ('FULC_int01    ','W/m2    ',pverp,'A','Longwave clear-sky upward flux, spectral interval 01',phys_decomp)
    call addfld ('FDLC_int01    ','W/m2    ',pverp,'A','Longwave clear-sky downward flux, spectral interval 01',phys_decomp)
    call addfld ('FUL_toa_int01     ','W/m2    ',1,'A','Longwave upward flux, spectral interval 01, toa',phys_decomp)
    call addfld ('FDL_toa_int01     ','W/m2    ',1,'A','Longwave downward flux, spectral interval 01, toa',phys_decomp)
    call addfld ('FULC_toa_int01    ','W/m2    ',1,'A','Longwave clear-sky upward flux, spectral interval 01, toa',phys_decomp)
    call addfld ('FDLC_toa_int01    ','W/m2    ',1,'A','Longwave clear-sky downward flux, spectral interval 01, toa',phys_decomp)

    call addfld ('FUL_int02     ','W/m2    ',pverp,'A','Longwave upward flux, spectral interval 02',phys_decomp)
    call addfld ('FDL_int02     ','W/m2    ',pverp,'A','Longwave downward flux, spectral interval 02',phys_decomp)
    call addfld ('FULC_int02    ','W/m2    ',pverp,'A','Longwave clear-sky upward flux, spectral interval 02',phys_decomp)
    call addfld ('FDLC_int02    ','W/m2    ',pverp,'A','Longwave clear-sky downward flux, spectral interval 02',phys_decomp)
    call addfld ('FUL_toa_int02     ','W/m2    ',1,'A','Longwave upward flux, spectral interval 02, toa',phys_decomp)
    call addfld ('FDL_toa_int02     ','W/m2    ',1,'A','Longwave downward flux, spectral interval 02, toa',phys_decomp)
    call addfld ('FULC_toa_int02    ','W/m2    ',1,'A','Longwave clear-sky upward flux, spectral interval 02, toa',phys_decomp)
    call addfld ('FDLC_toa_int02    ','W/m2    ',1,'A','Longwave clear-sky downward flux, spectral interval 02, toa',phys_decomp)

    call addfld ('FUL_int03     ','W/m2    ',pverp,'A','Longwave upward flux, spectral interval 03',phys_decomp)
    call addfld ('FDL_int03     ','W/m2    ',pverp,'A','Longwave downward flux, spectral interval 03',phys_decomp)
    call addfld ('FULC_int03    ','W/m2    ',pverp,'A','Longwave clear-sky upward flux, spectral interval 03',phys_decomp)
    call addfld ('FDLC_int03    ','W/m2    ',pverp,'A','Longwave clear-sky downward flux, spectral interval 03',phys_decomp)
    call addfld ('FUL_toa_int03     ','W/m2    ',1,'A','Longwave upward flux, spectral interval 03, toa',phys_decomp)
    call addfld ('FDL_toa_int03     ','W/m2    ',1,'A','Longwave downward flux, spectral interval 03, toa',phys_decomp)
    call addfld ('FULC_toa_int03    ','W/m2    ',1,'A','Longwave clear-sky upward flux, spectral interval 03, toa',phys_decomp)
    call addfld ('FDLC_toa_int03    ','W/m2    ',1,'A','Longwave clear-sky downward flux, spectral interval 03, toa',phys_decomp)

    call addfld ('FUL_int04     ','W/m2    ',pverp,'A','Longwave upward flux, spectral interval 04',phys_decomp)
    call addfld ('FDL_int04     ','W/m2    ',pverp,'A','Longwave downward flux, spectral interval 04',phys_decomp)
    call addfld ('FULC_int04    ','W/m2    ',pverp,'A','Longwave clear-sky upward flux, spectral interval 04',phys_decomp)
    call addfld ('FDLC_int04    ','W/m2    ',pverp,'A','Longwave clear-sky downward flux, spectral interval 04',phys_decomp)
    call addfld ('FUL_toa_int04     ','W/m2    ',1,'A','Longwave upward flux, spectral interval 04, toa',phys_decomp)
    call addfld ('FDL_toa_int04     ','W/m2    ',1,'A','Longwave downward flux, spectral interval 04, toa',phys_decomp)
    call addfld ('FULC_toa_int04    ','W/m2    ',1,'A','Longwave clear-sky upward flux, spectral interval 04, toa',phys_decomp)
    call addfld ('FDLC_toa_int04    ','W/m2    ',1,'A','Longwave clear-sky downward flux, spectral interval 04, toa',phys_decomp)

    call addfld ('FUL_int05     ','W/m2    ',pverp,'A','Longwave upward flux, spectral interval 05',phys_decomp)
    call addfld ('FDL_int05     ','W/m2    ',pverp,'A','Longwave downward flux, spectral interval 05',phys_decomp)
    call addfld ('FULC_int05    ','W/m2    ',pverp,'A','Longwave clear-sky upward flux, spectral interval 05',phys_decomp)
    call addfld ('FDLC_int05    ','W/m2    ',pverp,'A','Longwave clear-sky downward flux, spectral interval 05',phys_decomp)
    call addfld ('FUL_toa_int05     ','W/m2    ',1,'A','Longwave upward flux, spectral interval 05, toa',phys_decomp)
    call addfld ('FDL_toa_int05     ','W/m2    ',1,'A','Longwave downward flux, spectral interval 05, toa',phys_decomp)
    call addfld ('FULC_toa_int05    ','W/m2    ',1,'A','Longwave clear-sky upward flux, spectral interval 05, toa',phys_decomp)
    call addfld ('FDLC_toa_int05    ','W/m2    ',1,'A','Longwave clear-sky downward flux, spectral interval 05, toa',phys_decomp)

    call addfld ('FUL_int06     ','W/m2    ',pverp,'A','Longwave upward flux, spectral interval 06',phys_decomp)
    call addfld ('FDL_int06     ','W/m2    ',pverp,'A','Longwave downward flux, spectral interval 06',phys_decomp)
    call addfld ('FULC_int06    ','W/m2    ',pverp,'A','Longwave clear-sky upward flux, spectral interval 06',phys_decomp)
    call addfld ('FDLC_int06    ','W/m2    ',pverp,'A','Longwave clear-sky downward flux, spectral interval 06',phys_decomp)
    call addfld ('FUL_toa_int06     ','W/m2    ',1,'A','Longwave upward flux, spectral interval 06, toa',phys_decomp)
    call addfld ('FDL_toa_int06     ','W/m2    ',1,'A','Longwave downward flux, spectral interval 06, toa',phys_decomp)
    call addfld ('FULC_toa_int06    ','W/m2    ',1,'A','Longwave clear-sky upward flux, spectral interval 06, toa',phys_decomp)
    call addfld ('FDLC_toa_int06    ','W/m2    ',1,'A','Longwave clear-sky downward flux, spectral interval 06, toa',phys_decomp)

    call addfld ('FUL_int07     ','W/m2    ',pverp,'A','Longwave upward flux, spectral interval 07',phys_decomp)
    call addfld ('FDL_int07     ','W/m2    ',pverp,'A','Longwave downward flux, spectral interval 07',phys_decomp)
    call addfld ('FULC_int07    ','W/m2    ',pverp,'A','Longwave clear-sky upward flux, spectral interval 07',phys_decomp)
    call addfld ('FDLC_int07    ','W/m2    ',pverp,'A','Longwave clear-sky downward flux, spectral interval 07',phys_decomp)
    call addfld ('FUL_toa_int07     ','W/m2    ',1,'A','Longwave upward flux, spectral interval 07, toa',phys_decomp)
    call addfld ('FDL_toa_int07     ','W/m2    ',1,'A','Longwave downward flux, spectral interval 07, toa',phys_decomp)
    call addfld ('FULC_toa_int07    ','W/m2    ',1,'A','Longwave clear-sky upward flux, spectral interval 07, toa',phys_decomp)
    call addfld ('FDLC_toa_int07    ','W/m2    ',1,'A','Longwave clear-sky downward flux, spectral interval 07, toa',phys_decomp)

    call addfld ('FUL_int08     ','W/m2    ',pverp,'A','Longwave upward flux, spectral interval 08',phys_decomp)
    call addfld ('FDL_int08     ','W/m2    ',pverp,'A','Longwave downward flux, spectral interval 08',phys_decomp)
    call addfld ('FULC_int08    ','W/m2    ',pverp,'A','Longwave clear-sky upward flux, spectral interval 08',phys_decomp)
    call addfld ('FDLC_int08    ','W/m2    ',pverp,'A','Longwave clear-sky downward flux, spectral interval 08',phys_decomp)
    call addfld ('FUL_toa_int08     ','W/m2    ',1,'A','Longwave upward flux, spectral interval 08, toa',phys_decomp)
    call addfld ('FDL_toa_int08     ','W/m2    ',1,'A','Longwave downward flux, spectral interval 08, toa',phys_decomp)
    call addfld ('FULC_toa_int08    ','W/m2    ',1,'A','Longwave clear-sky upward flux, spectral interval 08, toa',phys_decomp)
    call addfld ('FDLC_toa_int08    ','W/m2    ',1,'A','Longwave clear-sky downward flux, spectral interval 08, toa',phys_decomp)

    call addfld ('FUL_int09     ','W/m2    ',pverp,'A','Longwave upward flux, spectral interval 09',phys_decomp)
    call addfld ('FDL_int09     ','W/m2    ',pverp,'A','Longwave downward flux, spectral interval 09',phys_decomp)
    call addfld ('FULC_int09    ','W/m2    ',pverp,'A','Longwave clear-sky upward flux, spectral interval 09',phys_decomp)
    call addfld ('FDLC_int09    ','W/m2    ',pverp,'A','Longwave clear-sky downward flux, spectral interval 09',phys_decomp)
    call addfld ('FUL_toa_int09     ','W/m2    ',1,'A','Longwave upward flux, spectral interval 09, toa',phys_decomp)
    call addfld ('FDL_toa_int09     ','W/m2    ',1,'A','Longwave downward flux, spectral interval 09, toa',phys_decomp)
    call addfld ('FULC_toa_int09    ','W/m2    ',1,'A','Longwave clear-sky upward flux, spectral interval 09, toa',phys_decomp)
    call addfld ('FDLC_toa_int09    ','W/m2    ',1,'A','Longwave clear-sky downward flux, spectral interval 09, toa',phys_decomp)

    call addfld ('FUL_int10     ','W/m2    ',pverp,'A','Longwave upward flux, spectral interval 10',phys_decomp)
    call addfld ('FDL_int10     ','W/m2    ',pverp,'A','Longwave downward flux, spectral interval 10',phys_decomp)
    call addfld ('FULC_int10    ','W/m2    ',pverp,'A','Longwave clear-sky upward flux, spectral interval 10',phys_decomp)
    call addfld ('FDLC_int10    ','W/m2    ',pverp,'A','Longwave clear-sky downward flux, spectral interval 10',phys_decomp)
    call addfld ('FUL_toa_int10     ','W/m2    ',1,'A','Longwave upward flux, spectral interval 10, toa',phys_decomp)
    call addfld ('FDL_toa_int10     ','W/m2    ',1,'A','Longwave downward flux, spectral interval 10, toa',phys_decomp)
    call addfld ('FULC_toa_int10    ','W/m2    ',1,'A','Longwave clear-sky upward flux, spectral interval 10, toa',phys_decomp)
    call addfld ('FDLC_toa_int10    ','W/m2    ',1,'A','Longwave clear-sky downward flux, spectral interval 10, toa',phys_decomp)

    call addfld ('FUL_int11     ','W/m2    ',pverp,'A','Longwave upward flux, spectral interval 11',phys_decomp)
    call addfld ('FDL_int11     ','W/m2    ',pverp,'A','Longwave downward flux, spectral interval 11',phys_decomp)
    call addfld ('FULC_int11    ','W/m2    ',pverp,'A','Longwave clear-sky upward flux, spectral interval 11',phys_decomp)
    call addfld ('FDLC_int11    ','W/m2    ',pverp,'A','Longwave clear-sky downward flux, spectral interval 11',phys_decomp)
    call addfld ('FUL_toa_int11     ','W/m2    ',1,'A','Longwave upward flux, spectral interval 11, toa',phys_decomp)
    call addfld ('FDL_toa_int11     ','W/m2    ',1,'A','Longwave downward flux, spectral interval 11, toa',phys_decomp)
    call addfld ('FULC_toa_int11    ','W/m2    ',1,'A','Longwave clear-sky upward flux, spectral interval 11, toa',phys_decomp)
    call addfld ('FDLC_toa_int11    ','W/m2    ',1,'A','Longwave clear-sky downward flux, spectral interval 11, toa',phys_decomp)

    call addfld ('FUL_int12     ','W/m2    ',pverp,'A','Longwave upward flux, spectral interval 12',phys_decomp)
    call addfld ('FDL_int12     ','W/m2    ',pverp,'A','Longwave downward flux, spectral interval 12',phys_decomp)
    call addfld ('FULC_int12    ','W/m2    ',pverp,'A','Longwave clear-sky upward flux, spectral interval 12',phys_decomp)
    call addfld ('FDLC_int12    ','W/m2    ',pverp,'A','Longwave clear-sky downward flux, spectral interval 12',phys_decomp)
    call addfld ('FUL_toa_int12     ','W/m2    ',1,'A','Longwave upward flux, spectral interval 12, toa',phys_decomp)
    call addfld ('FDL_toa_int12     ','W/m2    ',1,'A','Longwave downward flux, spectral interval 12, toa',phys_decomp)
    call addfld ('FULC_toa_int12    ','W/m2    ',1,'A','Longwave clear-sky upward flux, spectral interval 12, toa',phys_decomp)
    call addfld ('FDLC_toa_int12    ','W/m2    ',1,'A','Longwave clear-sky downward flux, spectral interval 12, toa',phys_decomp)

    call addfld ('FUL_int13     ','W/m2    ',pverp,'A','Longwave upward flux, spectral interval 13',phys_decomp)
    call addfld ('FDL_int13     ','W/m2    ',pverp,'A','Longwave downward flux, spectral interval 13',phys_decomp)
    call addfld ('FULC_int13    ','W/m2    ',pverp,'A','Longwave clear-sky upward flux, spectral interval 13',phys_decomp)
    call addfld ('FDLC_int13    ','W/m2    ',pverp,'A','Longwave clear-sky downward flux, spectral interval 13',phys_decomp)
    call addfld ('FUL_toa_int13     ','W/m2    ',1,'A','Longwave upward flux, spectral interval 13, toa',phys_decomp)
    call addfld ('FDL_toa_int13     ','W/m2    ',1,'A','Longwave downward flux, spectral interval 13, toa',phys_decomp)
    call addfld ('FULC_toa_int13    ','W/m2    ',1,'A','Longwave clear-sky upward flux, spectral interval 13, toa',phys_decomp)
    call addfld ('FDLC_toa_int13    ','W/m2    ',1,'A','Longwave clear-sky downward flux, spectral interval 13, toa',phys_decomp)

    call addfld ('FUL_int14     ','W/m2    ',pverp,'A','Longwave upward flux, spectral interval 14',phys_decomp)
    call addfld ('FDL_int14     ','W/m2    ',pverp,'A','Longwave downward flux, spectral interval 14',phys_decomp)
    call addfld ('FULC_int14    ','W/m2    ',pverp,'A','Longwave clear-sky upward flux, spectral interval 14',phys_decomp)
    call addfld ('FDLC_int14    ','W/m2    ',pverp,'A','Longwave clear-sky downward flux, spectral interval 14',phys_decomp)
    call addfld ('FUL_toa_int14     ','W/m2    ',1,'A','Longwave upward flux, spectral interval 13, toa',phys_decomp)
    call addfld ('FDL_toa_int14     ','W/m2    ',1,'A','Longwave downward flux, spectral interval 13, toa',phys_decomp)
    call addfld ('FULC_toa_int14    ','W/m2    ',1,'A','Longwave clear-sky upward flux, spectral interval 13, toa',phys_decomp)
    call addfld ('FDLC_toa_int14    ','W/m2    ',1,'A','Longwave clear-sky downward flux, spectral interval 13, toa',phys_decomp)

    call addfld ('FUL_int15     ','W/m2    ',pverp,'A','Longwave upward flux, spectral interval 15',phys_decomp)
    call addfld ('FDL_int15     ','W/m2    ',pverp,'A','Longwave downward flux, spectral interval 15',phys_decomp)
    call addfld ('FULC_int15    ','W/m2    ',pverp,'A','Longwave clear-sky upward flux, spectral interval 15',phys_decomp)
    call addfld ('FDLC_int15    ','W/m2    ',pverp,'A','Longwave clear-sky downward flux, spectral interval 15',phys_decomp)
    call addfld ('FUL_toa_int15     ','W/m2    ',1,'A','Longwave upward flux, spectral interval 15, toa',phys_decomp)
    call addfld ('FDL_toa_int15     ','W/m2    ',1,'A','Longwave downward flux, spectral interval 15, toa',phys_decomp)
    call addfld ('FULC_toa_int15    ','W/m2    ',1,'A','Longwave clear-sky upward flux, spectral interval 15, toa',phys_decomp)
    call addfld ('FDLC_toa_int15    ','W/m2    ',1,'A','Longwave clear-sky downward flux, spectral interval 15, toa',phys_decomp)

    call addfld ('FUL_int16     ','W/m2    ',pverp,'A','Longwave upward flux, spectral interval 16',phys_decomp)
    call addfld ('FDL_int16     ','W/m2    ',pverp,'A','Longwave downward flux, spectral interval 16',phys_decomp)
    call addfld ('FULC_int16    ','W/m2    ',pverp,'A','Longwave clear-sky upward flux, spectral interval 16',phys_decomp)
    call addfld ('FDLC_int16    ','W/m2    ',pverp,'A','Longwave clear-sky downward flux, spectral interval 16',phys_decomp)
    call addfld ('FUL_toa_int16     ','W/m2    ',1,'A','Longwave upward flux, spectral interval 16, toa',phys_decomp)
    call addfld ('FDL_toa_int16     ','W/m2    ',1,'A','Longwave downward flux, spectral interval 16, toa',phys_decomp)
    call addfld ('FULC_toa_int16    ','W/m2    ',1,'A','Longwave clear-sky upward flux, spectral interval 16, toa',phys_decomp)
    call addfld ('FDLC_toa_int16    ','W/m2    ',1,'A','Longwave clear-sky downward flux, spectral interval 16, toa',phys_decomp)

    call addfld ('FUL_int17     ','W/m2    ',pverp,'A','Longwave upward flux, spectral interval 17',phys_decomp)
    call addfld ('FDL_int17     ','W/m2    ',pverp,'A','Longwave downward flux, spectral interval 17',phys_decomp)
    call addfld ('FULC_int17    ','W/m2    ',pverp,'A','Longwave clear-sky upward flux, spectral interval 17',phys_decomp)
    call addfld ('FDLC_int17    ','W/m2    ',pverp,'A','Longwave clear-sky downward flux, spectral interval 17',phys_decomp)
    call addfld ('FUL_toa_int17     ','W/m2    ',1,'A','Longwave upward flux, spectral interval 17, toa',phys_decomp)
    call addfld ('FDL_toa_int17     ','W/m2    ',1,'A','Longwave downward flux, spectral interval 17, toa',phys_decomp)
    call addfld ('FULC_toa_int17    ','W/m2    ',1,'A','Longwave clear-sky upward flux, spectral interval 17, toa',phys_decomp)
    call addfld ('FDLC_toa_int17    ','W/m2    ',1,'A','Longwave clear-sky downward flux, spectral interval 17, toa',phys_decomp)

    call addfld ('FUL_int18     ','W/m2    ',pverp,'A','Longwave upward flux, spectral interval 18',phys_decomp)
    call addfld ('FDL_int18     ','W/m2    ',pverp,'A','Longwave downward flux, spectral interval 18',phys_decomp)
    call addfld ('FULC_int18    ','W/m2    ',pverp,'A','Longwave clear-sky upward flux, spectral interval 18',phys_decomp)
    call addfld ('FDLC_int18    ','W/m2    ',pverp,'A','Longwave clear-sky downward flux, spectral interval 18',phys_decomp)
    call addfld ('FUL_toa_int18     ','W/m2    ',1,'A','Longwave upward flux, spectral interval 18, toa',phys_decomp)
    call addfld ('FDL_toa_int18     ','W/m2    ',1,'A','Longwave downward flux, spectral interval 18, toa',phys_decomp)
    call addfld ('FULC_toa_int18    ','W/m2    ',1,'A','Longwave clear-sky upward flux, spectral interval 18, toa',phys_decomp)
    call addfld ('FDLC_toa_int18    ','W/m2    ',1,'A','Longwave clear-sky downward flux, spectral interval 18, toa',phys_decomp)

    call addfld ('FUL_int19     ','W/m2    ',pverp,'A','Longwave upward flux, spectral interval 19',phys_decomp)
    call addfld ('FDL_int19     ','W/m2    ',pverp,'A','Longwave downward flux, spectral interval 19',phys_decomp)
    call addfld ('FULC_int19    ','W/m2    ',pverp,'A','Longwave clear-sky upward flux, spectral interval 19',phys_decomp)
    call addfld ('FDLC_int19    ','W/m2    ',pverp,'A','Longwave clear-sky downward flux, spectral interval 19',phys_decomp)
    call addfld ('FUL_toa_int19     ','W/m2    ',1,'A','Longwave upward flux, spectral interval 19, toa',phys_decomp)
    call addfld ('FDL_toa_int19     ','W/m2    ',1,'A','Longwave downward flux, spectral interval 19, toa',phys_decomp)
    call addfld ('FULC_toa_int19    ','W/m2    ',1,'A','Longwave clear-sky upward flux, spectral interval 19, toa',phys_decomp)
    call addfld ('FDLC_toa_int19    ','W/m2    ',1,'A','Longwave clear-sky downward flux, spectral interval 19, toa',phys_decomp)

    call addfld ('FUL_int20     ','W/m2    ',pverp,'A','Longwave upward flux, spectral interval 20',phys_decomp)
    call addfld ('FDL_int20     ','W/m2    ',pverp,'A','Longwave downward flux, spectral interval 20',phys_decomp)
    call addfld ('FULC_int20    ','W/m2    ',pverp,'A','Longwave clear-sky upward flux, spectral interval 20',phys_decomp)
    call addfld ('FDLC_int20    ','W/m2    ',pverp,'A','Longwave clear-sky downward flux, spectral interval 20',phys_decomp)
    call addfld ('FUL_toa_int20     ','W/m2    ',1,'A','Longwave upward flux, spectral interval 20, toa',phys_decomp)
    call addfld ('FDL_toa_int20     ','W/m2    ',1,'A','Longwave downward flux, spectral interval 20, toa',phys_decomp)
    call addfld ('FULC_toa_int20    ','W/m2    ',1,'A','Longwave clear-sky upward flux, spectral interval 20, toa',phys_decomp)
    call addfld ('FDLC_toa_int20    ','W/m2    ',1,'A','Longwave clear-sky downward flux, spectral interval 20, toa',phys_decomp)

    call addfld ('FUL_int21     ','W/m2    ',pverp,'A','Longwave upward flux, spectral interval 21',phys_decomp)
    call addfld ('FDL_int21     ','W/m2    ',pverp,'A','Longwave downward flux, spectral interval 21',phys_decomp)
    call addfld ('FULC_int21    ','W/m2    ',pverp,'A','Longwave clear-sky upward flux, spectral interval 21',phys_decomp)
    call addfld ('FDLC_int21    ','W/m2    ',pverp,'A','Longwave clear-sky downward flux, spectral interval 21',phys_decomp)
    call addfld ('FUL_toa_int21     ','W/m2    ',1,'A','Longwave upward flux, spectral interval 21, toa',phys_decomp)
    call addfld ('FDL_toa_int21     ','W/m2    ',1,'A','Longwave downward flux, spectral interval 21, toa',phys_decomp)
    call addfld ('FULC_toa_int21    ','W/m2    ',1,'A','Longwave clear-sky upward flux, spectral interval 21, toa',phys_decomp)
    call addfld ('FDLC_toa_int21    ','W/m2    ',1,'A','Longwave clear-sky downward flux, spectral interval 21, toa',phys_decomp)

    call addfld ('FUL_int22     ','W/m2    ',pverp,'A','Longwave upward flux, spectral interval 22',phys_decomp)
    call addfld ('FDL_int22     ','W/m2    ',pverp,'A','Longwave downward flux, spectral interval 22',phys_decomp)
    call addfld ('FULC_int22    ','W/m2    ',pverp,'A','Longwave clear-sky upward flux, spectral interval 22',phys_decomp)
    call addfld ('FDLC_int22    ','W/m2    ',pverp,'A','Longwave clear-sky downward flux, spectral interval 22',phys_decomp)
    call addfld ('FUL_toa_int22     ','W/m2    ',1,'A','Longwave upward flux, spectral interval 22, toa',phys_decomp)
    call addfld ('FDL_toa_int22     ','W/m2    ',1,'A','Longwave downward flux, spectral interval 22, toa',phys_decomp)
    call addfld ('FULC_toa_int22    ','W/m2    ',1,'A','Longwave clear-sky upward flux, spectral interval 22, toa',phys_decomp)
    call addfld ('FDLC_toa_int22    ','W/m2    ',1,'A','Longwave clear-sky downward flux, spectral interval 22 toa',phys_decomp)

    call addfld ('FUL_int23     ','W/m2    ',pverp,'A','Longwave upward flux, spectral interval 23',phys_decomp)
    call addfld ('FDL_int23     ','W/m2    ',pverp,'A','Longwave downward flux, spectral interval 23',phys_decomp)
    call addfld ('FULC_int23    ','W/m2    ',pverp,'A','Longwave clear-sky upward flux, spectral interval 23',phys_decomp)
    call addfld ('FDLC_int23    ','W/m2    ',pverp,'A','Longwave clear-sky downward flux, spectral interval 23',phys_decomp)
    call addfld ('FUL_toa_int23     ','W/m2    ',1,'A','Longwave upward flux, spectral interval 23, toa',phys_decomp)
    call addfld ('FDL_toa_int23     ','W/m2    ',1,'A','Longwave downward flux, spectral interval 23, toa',phys_decomp)
    call addfld ('FULC_toa_int23    ','W/m2    ',1,'A','Longwave clear-sky upward flux, spectral interval 23, toa',phys_decomp)
    call addfld ('FDLC_toa_int23    ','W/m2    ',1,'A','Longwave clear-sky downward flux, spectral interval 23, toa',phys_decomp)

    call addfld ('FUL_int24     ','W/m2    ',pverp,'A','Longwave upward flux, spectral interval 24',phys_decomp)
    call addfld ('FDL_int24     ','W/m2    ',pverp,'A','Longwave downward flux, spectral interval 24',phys_decomp)
    call addfld ('FULC_int24    ','W/m2    ',pverp,'A','Longwave clear-sky upward flux, spectral interval 24',phys_decomp)
    call addfld ('FDLC_int24    ','W/m2    ',pverp,'A','Longwave clear-sky downward flux, spectral interval 24',phys_decomp)
    call addfld ('FUL_toa_int24     ','W/m2    ',1,'A','Longwave upward flux, spectral interval 24, toa',phys_decomp)
    call addfld ('FDL_toa_int24     ','W/m2    ',1,'A','Longwave downward flux, spectral interval 24, toa',phys_decomp)
    call addfld ('FULC_toa_int24    ','W/m2    ',1,'A','Longwave clear-sky upward flux, spectral interval 24, toa',phys_decomp)
    call addfld ('FDLC_toa_int24    ','W/m2    ',1,'A','Longwave clear-sky downward flux, spectral interval 24, toa',phys_decomp)

    call addfld ('FUL_int25     ','W/m2    ',pverp,'A','Longwave upward flux, spectral interval 25',phys_decomp)
    call addfld ('FDL_int25     ','W/m2    ',pverp,'A','Longwave downward flux, spectral interval 25',phys_decomp)
    call addfld ('FULC_int25    ','W/m2    ',pverp,'A','Longwave clear-sky upward flux, spectral interval 25',phys_decomp)
    call addfld ('FDLC_int25    ','W/m2    ',pverp,'A','Longwave clear-sky downward flux, spectral interval 25',phys_decomp)
    call addfld ('FUL_toa_int25     ','W/m2    ',1,'A','Longwave upward flux, spectral interval 25, toa',phys_decomp)
    call addfld ('FDL_toa_int25     ','W/m2    ',1,'A','Longwave downward flux, spectral interval 25, toa',phys_decomp)
    call addfld ('FULC_toa_int25    ','W/m2    ',1,'A','Longwave clear-sky upward flux, spectral interval 25, toa',phys_decomp)
    call addfld ('FDLC_toa_int25    ','W/m2    ',1,'A','Longwave clear-sky downward flux, spectral interval 25, toa',phys_decomp)

    call addfld ('FUL_int26     ','W/m2    ',pverp,'A','Longwave upward flux, spectral interval 26',phys_decomp)
    call addfld ('FDL_int26     ','W/m2    ',pverp,'A','Longwave downward flux, spectral interval 26',phys_decomp)
    call addfld ('FULC_int26    ','W/m2    ',pverp,'A','Longwave clear-sky upward flux, spectral interval 26',phys_decomp)
    call addfld ('FDLC_int26    ','W/m2    ',pverp,'A','Longwave clear-sky downward flux, spectral interval 26',phys_decomp)
    call addfld ('FUL_toa_int26     ','W/m2    ',1,'A','Longwave upward flux, spectral interval 26, toa',phys_decomp)
    call addfld ('FDL_toa_int26     ','W/m2    ',1,'A','Longwave downward flux, spectral interval 26, toa',phys_decomp)
    call addfld ('FULC_toa_int26    ','W/m2    ',1,'A','Longwave clear-sky upward flux, spectral interval 26, toa',phys_decomp)
    call addfld ('FDLC_toa_int26    ','W/m2    ',1,'A','Longwave clear-sky downward flux, spectral interval 26, toa',phys_decomp)

    call addfld ('FUL_int27     ','W/m2    ',pverp,'A','Longwave upward flux, spectral interval 27',phys_decomp)
    call addfld ('FDL_int27     ','W/m2    ',pverp,'A','Longwave downward flux, spectral interval 27',phys_decomp)
    call addfld ('FULC_int27    ','W/m2    ',pverp,'A','Longwave clear-sky upward flux, spectral interval 27',phys_decomp)
    call addfld ('FDLC_int27    ','W/m2    ',pverp,'A','Longwave clear-sky downward flux, spectral interval 27',phys_decomp)
    call addfld ('FUL_toa_int27     ','W/m2    ',1,'A','Longwave upward flux, spectral interval 27, toa',phys_decomp)
    call addfld ('FDL_toa_int27     ','W/m2    ',1,'A','Longwave downward flux, spectral interval 27, toa',phys_decomp)
    call addfld ('FULC_toa_int27    ','W/m2    ',1,'A','Longwave clear-sky upward flux, spectral interval 27, toa',phys_decomp)
    call addfld ('FDLC_toa_int27    ','W/m2    ',1,'A','Longwave clear-sky downward flux, spectral interval 27, toa',phys_decomp)

    call addfld ('FUL_int28     ','W/m2    ',pverp,'A','Longwave upward flux, spectral interval 28',phys_decomp)
    call addfld ('FDL_int28     ','W/m2    ',pverp,'A','Longwave downward flux, spectral interval 28',phys_decomp)
    call addfld ('FULC_int28    ','W/m2    ',pverp,'A','Longwave clear-sky upward flux, spectral interval 28',phys_decomp)
    call addfld ('FDLC_int28    ','W/m2    ',pverp,'A','Longwave clear-sky downward flux, spectral interval 28',phys_decomp)
    call addfld ('FUL_toa_int28     ','W/m2    ',1,'A','Longwave upward flux, spectral interval 28, toa',phys_decomp)
    call addfld ('FDL_toa_int28     ','W/m2    ',1,'A','Longwave downward flux, spectral interval 28, toa',phys_decomp)
    call addfld ('FULC_toa_int28    ','W/m2    ',1,'A','Longwave clear-sky upward flux, spectral interval 28, toa',phys_decomp)
    call addfld ('FDLC_toa_int28    ','W/m2    ',1,'A','Longwave clear-sky downward flux, spectral interval 28, toa',phys_decomp)

  end subroutine addfld_spectral_intervals



!============================================================================
 
  subroutine outfld_spectral_flux_fullsky(lchnk, lwdown_rad_spec_in, lwup_rad_spec_in, swup_rad_spec_in, swdown_rad_spec_in )

!------------------------------------------------------------------------
!
! Purpose:  Add spectral output to master field list
!
!------------------------------------------------------------------------
   use cam_history,       only: outfld
!------------------------------------------------------------------------
!
! Arguments
!
    integer,  intent(in) :: lchnk
    real(r8), intent(in), dimension(pcols,pverp,ntot_wavlnrng) ::  lwdown_rad_spec_in
    real(r8), intent(in), dimension(pcols,pverp,ntot_wavlnrng) ::  lwup_rad_spec_in
    real(r8), intent(in), dimension(pcols,pverp,ntot_wavlnrng) ::  swup_rad_spec_in
    real(r8), intent(in), dimension(pcols,pverp,ntot_wavlnrng) ::  swdown_rad_spec_in

!------------------------------------------------------------------------
!
! Start Code
!

    ! shortwave fields
    call outfld('FUS_int01     ',swup_rad_spec_in(:,:,1), pcols, lchnk)
    call outfld('FDS_int01     ',swdown_rad_spec_in(:,:,1), pcols, lchnk)
    call outfld('FUS_int02     ',swup_rad_spec_in(:,:,2), pcols, lchnk)
    call outfld('FDS_int02     ',swdown_rad_spec_in(:,:,2), pcols, lchnk)
    call outfld('FUS_int03     ',swup_rad_spec_in(:,:,3), pcols, lchnk)
    call outfld('FDS_int03     ',swdown_rad_spec_in(:,:,3), pcols, lchnk)
    call outfld('FUS_int04     ',swup_rad_spec_in(:,:,4), pcols, lchnk)
    call outfld('FDS_int04     ',swdown_rad_spec_in(:,:,4), pcols, lchnk)
    call outfld('FUS_int05     ',swup_rad_spec_in(:,:,5), pcols, lchnk)
    call outfld('FDS_int05     ',swdown_rad_spec_in(:,:,5), pcols, lchnk)
    call outfld('FUS_int06     ',swup_rad_spec_in(:,:,6), pcols, lchnk)
    call outfld('FDS_int06     ',swdown_rad_spec_in(:,:,6), pcols, lchnk)
    call outfld('FUS_int07     ',swup_rad_spec_in(:,:,7), pcols, lchnk)
    call outfld('FDS_int07     ',swdown_rad_spec_in(:,:,7), pcols, lchnk)
    call outfld('FUS_int08     ',swup_rad_spec_in(:,:,8), pcols, lchnk)
    call outfld('FDS_int08     ',swdown_rad_spec_in(:,:,8), pcols, lchnk)
    call outfld('FUS_int09     ',swup_rad_spec_in(:,:,9), pcols, lchnk)
    call outfld('FDS_int09     ',swdown_rad_spec_in(:,:,9), pcols, lchnk)
    call outfld('FUS_int10     ',swup_rad_spec_in(:,:,10), pcols, lchnk)
    call outfld('FDS_int10     ',swdown_rad_spec_in(:,:,10), pcols, lchnk)
    call outfld('FUS_int11     ',swup_rad_spec_in(:,:,11), pcols, lchnk)
    call outfld('FDS_int11     ',swdown_rad_spec_in(:,:,11), pcols, lchnk)
    call outfld('FUS_int12     ',swup_rad_spec_in(:,:,12), pcols, lchnk)
    call outfld('FDS_int12     ',swdown_rad_spec_in(:,:,12), pcols, lchnk)
    call outfld('FUS_int13     ',swup_rad_spec_in(:,:,13), pcols, lchnk)
    call outfld('FDS_int13     ',swdown_rad_spec_in(:,:,13), pcols, lchnk)
    call outfld('FUS_int14     ',swup_rad_spec_in(:,:,14), pcols, lchnk)
    call outfld('FDS_int14     ',swdown_rad_spec_in(:,:,14), pcols, lchnk)
    call outfld('FUS_int15     ',swup_rad_spec_in(:,:,15), pcols, lchnk)
    call outfld('FDS_int15     ',swdown_rad_spec_in(:,:,15), pcols, lchnk)
    call outfld('FUS_int16     ',swup_rad_spec_in(:,:,16), pcols, lchnk)
    call outfld('FDS_int16     ',swdown_rad_spec_in(:,:,16), pcols, lchnk)
    call outfld('FUS_int17     ',swup_rad_spec_in(:,:,17), pcols, lchnk)
    call outfld('FDS_int17     ',swdown_rad_spec_in(:,:,17), pcols, lchnk)
    call outfld('FUS_int18     ',swup_rad_spec_in(:,:,18), pcols, lchnk)
    call outfld('FDS_int18     ',swdown_rad_spec_in(:,:,18), pcols, lchnk)
    call outfld('FUS_int19     ',swup_rad_spec_in(:,:,19), pcols, lchnk)
    call outfld('FDS_int19     ',swdown_rad_spec_in(:,:,19), pcols, lchnk)
    call outfld('FUS_int20     ',swup_rad_spec_in(:,:,20), pcols, lchnk)
    call outfld('FDS_int20     ',swdown_rad_spec_in(:,:,20), pcols, lchnk)
    call outfld('FUS_int21     ',swup_rad_spec_in(:,:,21), pcols, lchnk)
    call outfld('FDS_int21     ',swdown_rad_spec_in(:,:,21), pcols, lchnk)
    call outfld('FUS_int22     ',swup_rad_spec_in(:,:,22), pcols, lchnk)
    call outfld('FDS_int22     ',swdown_rad_spec_in(:,:,22), pcols, lchnk)
    call outfld('FUS_int23     ',swup_rad_spec_in(:,:,23), pcols, lchnk)
    call outfld('FDS_int23     ',swdown_rad_spec_in(:,:,23), pcols, lchnk)
    call outfld('FUS_int24     ',swup_rad_spec_in(:,:,24), pcols, lchnk)
    call outfld('FDS_int24     ',swdown_rad_spec_in(:,:,24), pcols, lchnk)
    call outfld('FUS_int25     ',swup_rad_spec_in(:,:,25), pcols, lchnk)
    call outfld('FDS_int25     ',swdown_rad_spec_in(:,:,25), pcols, lchnk)
    call outfld('FUS_int26     ',swup_rad_spec_in(:,:,26), pcols, lchnk)
    call outfld('FDS_int26     ',swdown_rad_spec_in(:,:,26), pcols, lchnk)
    call outfld('FUS_int27     ',swup_rad_spec_in(:,:,27), pcols, lchnk)
    call outfld('FDS_int27     ',swdown_rad_spec_in(:,:,27), pcols, lchnk)
    call outfld('FUS_int28     ',swup_rad_spec_in(:,:,28), pcols, lchnk)
    call outfld('FDS_int28     ',swdown_rad_spec_in(:,:,28), pcols, lchnk)

    call outfld('FUS_toa_int01     ',swup_rad_spec_in(:,1,1), pcols, lchnk)
    call outfld('FDS_toa_int01     ',swdown_rad_spec_in(:,1,1), pcols, lchnk)
    call outfld('FUS_toa_int02     ',swup_rad_spec_in(:,1,2), pcols, lchnk)
    call outfld('FDS_toa_int02     ',swdown_rad_spec_in(:,1,2), pcols, lchnk)
    call outfld('FUS_toa_int03     ',swup_rad_spec_in(:,1,3), pcols, lchnk)
    call outfld('FDS_toa_int03     ',swdown_rad_spec_in(:,1,3), pcols, lchnk)
    call outfld('FUS_toa_int04     ',swup_rad_spec_in(:,1,4), pcols, lchnk)
    call outfld('FDS_toa_int04     ',swdown_rad_spec_in(:,1,4), pcols, lchnk)
    call outfld('FUS_toa_int05     ',swup_rad_spec_in(:,1,5), pcols, lchnk)
    call outfld('FDS_toa_int05     ',swdown_rad_spec_in(:,1,5), pcols, lchnk)
    call outfld('FUS_toa_int06     ',swup_rad_spec_in(:,1,6), pcols, lchnk)
    call outfld('FDS_toa_int06     ',swdown_rad_spec_in(:,1,6), pcols, lchnk)
    call outfld('FUS_toa_int07     ',swup_rad_spec_in(:,1,7), pcols, lchnk)
    call outfld('FDS_toa_int07     ',swdown_rad_spec_in(:,1,7), pcols, lchnk)
    call outfld('FUS_toa_int08     ',swup_rad_spec_in(:,1,8), pcols, lchnk)
    call outfld('FDS_toa_int08     ',swdown_rad_spec_in(:,1,8), pcols, lchnk)
    call outfld('FUS_toa_int09     ',swup_rad_spec_in(:,1,9), pcols, lchnk)
    call outfld('FDS_toa_int09     ',swdown_rad_spec_in(:,1,9), pcols, lchnk)
    call outfld('FUS_toa_int10     ',swup_rad_spec_in(:,1,10), pcols, lchnk)
    call outfld('FDS_toa_int10     ',swdown_rad_spec_in(:,1,10), pcols, lchnk)
    call outfld('FUS_toa_int11     ',swup_rad_spec_in(:,1,11), pcols, lchnk)
    call outfld('FDS_toa_int11     ',swdown_rad_spec_in(:,1,11), pcols, lchnk)
    call outfld('FUS_toa_int12     ',swup_rad_spec_in(:,1,12), pcols, lchnk)
    call outfld('FDS_toa_int12     ',swdown_rad_spec_in(:,1,12), pcols, lchnk)
    call outfld('FUS_toa_int13     ',swup_rad_spec_in(:,1,13), pcols, lchnk)
    call outfld('FDS_toa_int13     ',swdown_rad_spec_in(:,1,13), pcols, lchnk)
    call outfld('FUS_toa_int14     ',swup_rad_spec_in(:,1,14), pcols, lchnk)
    call outfld('FDS_toa_int14     ',swdown_rad_spec_in(:,1,14), pcols, lchnk)
    call outfld('FUS_toa_int15     ',swup_rad_spec_in(:,1,15), pcols, lchnk)
    call outfld('FDS_toa_int15     ',swdown_rad_spec_in(:,1,15), pcols, lchnk)
    call outfld('FUS_toa_int16     ',swup_rad_spec_in(:,1,16), pcols, lchnk)
    call outfld('FDS_toa_int16     ',swdown_rad_spec_in(:,1,16), pcols, lchnk)
    call outfld('FUS_toa_int17     ',swup_rad_spec_in(:,1,17), pcols, lchnk)
    call outfld('FDS_toa_int17     ',swdown_rad_spec_in(:,1,17), pcols, lchnk)
    call outfld('FUS_toa_int18     ',swup_rad_spec_in(:,1,18), pcols, lchnk)
    call outfld('FDS_toa_int18     ',swdown_rad_spec_in(:,1,18), pcols, lchnk)
    call outfld('FUS_toa_int19     ',swup_rad_spec_in(:,1,19), pcols, lchnk)
    call outfld('FDS_toa_int19     ',swdown_rad_spec_in(:,1,19), pcols, lchnk)
    call outfld('FUS_toa_int20     ',swup_rad_spec_in(:,1,20), pcols, lchnk)
    call outfld('FDS_toa_int20     ',swdown_rad_spec_in(:,1,20), pcols, lchnk)
    call outfld('FUS_toa_int21     ',swup_rad_spec_in(:,1,21), pcols, lchnk)
    call outfld('FDS_toa_int21     ',swdown_rad_spec_in(:,1,21), pcols, lchnk)
    call outfld('FUS_toa_int22     ',swup_rad_spec_in(:,1,22), pcols, lchnk)
    call outfld('FDS_toa_int22     ',swdown_rad_spec_in(:,1,22), pcols, lchnk)
    call outfld('FUS_toa_int23     ',swup_rad_spec_in(:,1,23), pcols, lchnk)
    call outfld('FDS_toa_int23     ',swdown_rad_spec_in(:,1,23), pcols, lchnk)
    call outfld('FUS_toa_int24     ',swup_rad_spec_in(:,1,24), pcols, lchnk)
    call outfld('FDS_toa_int24     ',swdown_rad_spec_in(:,1,24), pcols, lchnk)
    call outfld('FUS_toa_int25     ',swup_rad_spec_in(:,1,25), pcols, lchnk)
    call outfld('FDS_toa_int25     ',swdown_rad_spec_in(:,1,25), pcols, lchnk)
    call outfld('FUS_toa_int26     ',swup_rad_spec_in(:,1,26), pcols, lchnk)
    call outfld('FDS_toa_int26     ',swdown_rad_spec_in(:,1,26), pcols, lchnk)
    call outfld('FUS_toa_int27     ',swup_rad_spec_in(:,1,27), pcols, lchnk)
    call outfld('FDS_toa_int27     ',swdown_rad_spec_in(:,1,27), pcols, lchnk)
    call outfld('FUS_toa_int28     ',swup_rad_spec_in(:,1,28), pcols, lchnk)
    call outfld('FDS_toa_int28     ',swdown_rad_spec_in(:,1,28), pcols, lchnk)


    ! longwave
    call outfld('FUL_int01     ',lwup_rad_spec_in(:,:,1), pcols, lchnk)
    call outfld('FDL_int01     ',lwdown_rad_spec_in(:,:,1), pcols, lchnk)
    call outfld('FUL_int02     ',lwup_rad_spec_in(:,:,2), pcols, lchnk)
    call outfld('FDL_int02     ',lwdown_rad_spec_in(:,:,2), pcols, lchnk)
    call outfld('FUL_int03     ',lwup_rad_spec_in(:,:,3), pcols, lchnk)
    call outfld('FDL_int03     ',lwdown_rad_spec_in(:,:,3), pcols, lchnk)
    call outfld('FUL_int04     ',lwup_rad_spec_in(:,:,4), pcols, lchnk)
    call outfld('FDL_int04     ',lwdown_rad_spec_in(:,:,4), pcols, lchnk)
    call outfld('FUL_int05     ',lwup_rad_spec_in(:,:,5), pcols, lchnk)
    call outfld('FDL_int05     ',lwdown_rad_spec_in(:,:,5), pcols, lchnk)
    call outfld('FUL_int06     ',lwup_rad_spec_in(:,:,6), pcols, lchnk)
    call outfld('FDL_int06     ',lwdown_rad_spec_in(:,:,6), pcols, lchnk)
    call outfld('FUL_int07     ',lwup_rad_spec_in(:,:,7), pcols, lchnk)
    call outfld('FDL_int07     ',lwdown_rad_spec_in(:,:,7), pcols, lchnk)
    call outfld('FUL_int08     ',lwup_rad_spec_in(:,:,8), pcols, lchnk)
    call outfld('FDL_int08     ',lwdown_rad_spec_in(:,:,8), pcols, lchnk)
    call outfld('FUL_int09     ',lwup_rad_spec_in(:,:,9), pcols, lchnk)
    call outfld('FDL_int09     ',lwdown_rad_spec_in(:,:,9), pcols, lchnk)
    call outfld('FUL_int10     ',lwup_rad_spec_in(:,:,10), pcols, lchnk)
    call outfld('FDL_int10     ',lwdown_rad_spec_in(:,:,10), pcols, lchnk)
    call outfld('FUL_int11     ',lwup_rad_spec_in(:,:,11), pcols, lchnk)
    call outfld('FDL_int11     ',lwdown_rad_spec_in(:,:,11), pcols, lchnk)
    call outfld('FUL_int12     ',lwup_rad_spec_in(:,:,12), pcols, lchnk)
    call outfld('FDL_int12     ',lwdown_rad_spec_in(:,:,12), pcols, lchnk)
    call outfld('FUL_int13     ',lwup_rad_spec_in(:,:,13), pcols, lchnk)
    call outfld('FDL_int13     ',lwdown_rad_spec_in(:,:,13), pcols, lchnk)
    call outfld('FUL_int14     ',lwup_rad_spec_in(:,:,14), pcols, lchnk)
    call outfld('FDL_int14     ',lwdown_rad_spec_in(:,:,14), pcols, lchnk)
    call outfld('FUL_int15     ',lwup_rad_spec_in(:,:,15), pcols, lchnk)
    call outfld('FDL_int15     ',lwdown_rad_spec_in(:,:,15), pcols, lchnk)
    call outfld('FUL_int16     ',lwup_rad_spec_in(:,:,16), pcols, lchnk)
    call outfld('FDL_int16     ',lwdown_rad_spec_in(:,:,16), pcols, lchnk)
    call outfld('FUL_int17     ',lwup_rad_spec_in(:,:,17), pcols, lchnk)
    call outfld('FDL_int17     ',lwdown_rad_spec_in(:,:,17), pcols, lchnk)
    call outfld('FUL_int18     ',lwup_rad_spec_in(:,:,18), pcols, lchnk)
    call outfld('FDL_int18     ',lwdown_rad_spec_in(:,:,18), pcols, lchnk)
    call outfld('FUL_int19     ',lwup_rad_spec_in(:,:,19), pcols, lchnk)
    call outfld('FDL_int19     ',lwdown_rad_spec_in(:,:,19), pcols, lchnk)
    call outfld('FUL_int20     ',lwup_rad_spec_in(:,:,20), pcols, lchnk)
    call outfld('FDL_int20     ',lwdown_rad_spec_in(:,:,20), pcols, lchnk)
    call outfld('FUL_int21     ',lwup_rad_spec_in(:,:,21), pcols, lchnk)
    call outfld('FDL_int21     ',lwdown_rad_spec_in(:,:,21), pcols, lchnk)
    call outfld('FUL_int22     ',lwup_rad_spec_in(:,:,22), pcols, lchnk)
    call outfld('FDL_int22     ',lwdown_rad_spec_in(:,:,22), pcols, lchnk)
    call outfld('FUL_int23     ',lwup_rad_spec_in(:,:,23), pcols, lchnk)
    call outfld('FDL_int23     ',lwdown_rad_spec_in(:,:,23), pcols, lchnk)
    call outfld('FUL_int24     ',lwup_rad_spec_in(:,:,24), pcols, lchnk)
    call outfld('FDL_int24     ',lwdown_rad_spec_in(:,:,24), pcols, lchnk)
    call outfld('FUL_int25     ',lwup_rad_spec_in(:,:,25), pcols, lchnk)
    call outfld('FDL_int25     ',lwdown_rad_spec_in(:,:,25), pcols, lchnk)
    call outfld('FUL_int26     ',lwup_rad_spec_in(:,:,26), pcols, lchnk)
    call outfld('FDL_int26     ',lwdown_rad_spec_in(:,:,26), pcols, lchnk)
    call outfld('FUL_int27     ',lwup_rad_spec_in(:,:,27), pcols, lchnk)
    call outfld('FDL_int27     ',lwdown_rad_spec_in(:,:,27), pcols, lchnk)
    call outfld('FUL_int28     ',lwup_rad_spec_in(:,:,28), pcols, lchnk)
    call outfld('FDL_int28     ',lwdown_rad_spec_in(:,:,28), pcols, lchnk)

    call outfld('FUL_toa_int01     ',lwup_rad_spec_in(:,1,1), pcols, lchnk)
    call outfld('FDL_toa_int01     ',lwdown_rad_spec_in(:,1,1), pcols, lchnk)
    call outfld('FUL_toa_int02     ',lwup_rad_spec_in(:,1,2), pcols, lchnk)
    call outfld('FDL_toa_int02     ',lwdown_rad_spec_in(:,1,2), pcols, lchnk)
    call outfld('FUL_toa_int03     ',lwup_rad_spec_in(:,1,3), pcols, lchnk)
    call outfld('FDL_toa_int03     ',lwdown_rad_spec_in(:,1,3), pcols, lchnk)
    call outfld('FUL_toa_int04     ',lwup_rad_spec_in(:,1,4), pcols, lchnk)
    call outfld('FDL_toa_int04     ',lwdown_rad_spec_in(:,1,4), pcols, lchnk)
    call outfld('FUL_toa_int05     ',lwup_rad_spec_in(:,1,5), pcols, lchnk)
    call outfld('FDL_toa_int05     ',lwdown_rad_spec_in(:,1,5), pcols, lchnk)
    call outfld('FUL_toa_int06     ',lwup_rad_spec_in(:,1,6), pcols, lchnk)
    call outfld('FDL_toa_int06     ',lwdown_rad_spec_in(:,1,6), pcols, lchnk)
    call outfld('FUL_toa_int07     ',lwup_rad_spec_in(:,1,7), pcols, lchnk)
    call outfld('FDL_toa_int07     ',lwdown_rad_spec_in(:,1,7), pcols, lchnk)
    call outfld('FUL_toa_int08     ',lwup_rad_spec_in(:,1,8), pcols, lchnk)
    call outfld('FDL_toa_int08     ',lwdown_rad_spec_in(:,1,8), pcols, lchnk)
    call outfld('FUL_toa_int09     ',lwup_rad_spec_in(:,1,9), pcols, lchnk)
    call outfld('FDL_toa_int09     ',lwdown_rad_spec_in(:,1,9), pcols, lchnk)
    call outfld('FUL_toa_int10     ',lwup_rad_spec_in(:,1,10), pcols, lchnk)
    call outfld('FDL_toa_int10     ',lwdown_rad_spec_in(:,1,10), pcols, lchnk)
    call outfld('FUL_toa_int11     ',lwup_rad_spec_in(:,1,11), pcols, lchnk)
    call outfld('FDL_toa_int11     ',lwdown_rad_spec_in(:,1,11), pcols, lchnk)
    call outfld('FUL_toa_int12     ',lwup_rad_spec_in(:,1,12), pcols, lchnk)
    call outfld('FDL_toa_int12     ',lwdown_rad_spec_in(:,1,12), pcols, lchnk)
    call outfld('FUL_toa_int13     ',lwup_rad_spec_in(:,1,13), pcols, lchnk)
    call outfld('FDL_toa_int13     ',lwdown_rad_spec_in(:,1,13), pcols, lchnk)
    call outfld('FUL_toa_int14     ',lwup_rad_spec_in(:,1,14), pcols, lchnk)
    call outfld('FDL_toa_int14     ',lwdown_rad_spec_in(:,1,14), pcols, lchnk)
    call outfld('FUL_toa_int15     ',lwup_rad_spec_in(:,1,15), pcols, lchnk)
    call outfld('FDL_toa_int15     ',lwdown_rad_spec_in(:,1,15), pcols, lchnk)
    call outfld('FUL_toa_int16     ',lwup_rad_spec_in(:,1,16), pcols, lchnk)
    call outfld('FDL_toa_int16     ',lwdown_rad_spec_in(:,1,16), pcols, lchnk)
    call outfld('FUL_toa_int17     ',lwup_rad_spec_in(:,1,17), pcols, lchnk)
    call outfld('FDL_toa_int17     ',lwdown_rad_spec_in(:,1,17), pcols, lchnk)
    call outfld('FUL_toa_int18     ',lwup_rad_spec_in(:,1,18), pcols, lchnk)
    call outfld('FDL_toa_int18     ',lwdown_rad_spec_in(:,1,18), pcols, lchnk)
    call outfld('FUL_toa_int19     ',lwup_rad_spec_in(:,1,19), pcols, lchnk)
    call outfld('FDL_toa_int19     ',lwdown_rad_spec_in(:,1,19), pcols, lchnk)
    call outfld('FUL_toa_int20     ',lwup_rad_spec_in(:,1,20), pcols, lchnk)
    call outfld('FDL_toa_int20     ',lwdown_rad_spec_in(:,1,20), pcols, lchnk)
    call outfld('FUL_toa_int21     ',lwup_rad_spec_in(:,1,21), pcols, lchnk)
    call outfld('FDL_toa_int21     ',lwdown_rad_spec_in(:,1,21), pcols, lchnk)
    call outfld('FUL_toa_int22     ',lwup_rad_spec_in(:,1,22), pcols, lchnk)
    call outfld('FDL_toa_int22     ',lwdown_rad_spec_in(:,1,22), pcols, lchnk)
    call outfld('FUL_toa_int23     ',lwup_rad_spec_in(:,1,23), pcols, lchnk)
    call outfld('FDL_toa_int23     ',lwdown_rad_spec_in(:,1,23), pcols, lchnk)
    call outfld('FUL_toa_int24     ',lwup_rad_spec_in(:,1,24), pcols, lchnk)
    call outfld('FDL_toa_int24     ',lwdown_rad_spec_in(:,1,24), pcols, lchnk)
    call outfld('FUL_toa_int25     ',lwup_rad_spec_in(:,1,25), pcols, lchnk)
    call outfld('FDL_toa_int25     ',lwdown_rad_spec_in(:,1,25), pcols, lchnk)
    call outfld('FUL_toa_int26     ',lwup_rad_spec_in(:,1,26), pcols, lchnk)
    call outfld('FDL_toa_int26     ',lwdown_rad_spec_in(:,1,26), pcols, lchnk)
    call outfld('FUL_toa_int27     ',lwup_rad_spec_in(:,1,27), pcols, lchnk)
    call outfld('FDL_toa_int27     ',lwdown_rad_spec_in(:,1,27), pcols, lchnk)
    call outfld('FUL_toa_int28     ',lwup_rad_spec_in(:,1,28), pcols, lchnk)
    call outfld('FDL_toa_int28     ',lwdown_rad_spec_in(:,1,28), pcols, lchnk)

end subroutine outfld_spectral_flux_fullsky
               


!============================================================================
 
  subroutine outfld_spectral_flux_clearsky (lchnk, lwdown_rad_spec_in, lwup_rad_spec_in, swup_rad_spec_in, swdown_rad_spec_in )

!------------------------------------------------------------------------
!
! Purpose:  Add spectral output to master field list
!
!------------------------------------------------------------------------
   use cam_history,       only: outfld
!------------------------------------------------------------------------
!
! Arguments
!
    integer,  intent(in) :: lchnk
    real(r8), intent(in), dimension(pcols,pverp,ntot_wavlnrng) ::  lwdown_rad_spec_in
    real(r8), intent(in), dimension(pcols,pverp,ntot_wavlnrng) ::  lwup_rad_spec_in
    real(r8), intent(in), dimension(pcols,pverp,ntot_wavlnrng) ::  swup_rad_spec_in
    real(r8), intent(in), dimension(pcols,pverp,ntot_wavlnrng) ::  swdown_rad_spec_in

!------------------------------------------------------------------------
!
! Start Code
!

    ! shortwave fields
    call outfld('FUSC_int01     ',swup_rad_spec_in(:,:,1), pcols, lchnk)
    call outfld('FDSC_int01     ',swdown_rad_spec_in(:,:,1), pcols, lchnk)
    call outfld('FUSC_int02     ',swup_rad_spec_in(:,:,2), pcols, lchnk)
    call outfld('FDSC_int02     ',swdown_rad_spec_in(:,:,2), pcols, lchnk)
    call outfld('FUSC_int03     ',swup_rad_spec_in(:,:,3), pcols, lchnk)
    call outfld('FDSC_int03     ',swdown_rad_spec_in(:,:,3), pcols, lchnk)
    call outfld('FUSC_int04     ',swup_rad_spec_in(:,:,4), pcols, lchnk)
    call outfld('FDSC_int04     ',swdown_rad_spec_in(:,:,4), pcols, lchnk)
    call outfld('FUSC_int05     ',swup_rad_spec_in(:,:,5), pcols, lchnk)
    call outfld('FDSC_int05     ',swdown_rad_spec_in(:,:,5), pcols, lchnk)
    call outfld('FUSC_int06     ',swup_rad_spec_in(:,:,6), pcols, lchnk)
    call outfld('FDSC_int06     ',swdown_rad_spec_in(:,:,6), pcols, lchnk)
    call outfld('FUSC_int07     ',swup_rad_spec_in(:,:,7), pcols, lchnk)
    call outfld('FDSC_int07     ',swdown_rad_spec_in(:,:,7), pcols, lchnk)
    call outfld('FUSC_int08     ',swup_rad_spec_in(:,:,8), pcols, lchnk)
    call outfld('FDSC_int08     ',swdown_rad_spec_in(:,:,8), pcols, lchnk)
    call outfld('FUSC_int09     ',swup_rad_spec_in(:,:,9), pcols, lchnk)
    call outfld('FDSC_int09     ',swdown_rad_spec_in(:,:,9), pcols, lchnk)
    call outfld('FUSC_int10     ',swup_rad_spec_in(:,:,10), pcols, lchnk)
    call outfld('FDSC_int10     ',swdown_rad_spec_in(:,:,10), pcols, lchnk)
    call outfld('FUSC_int11     ',swup_rad_spec_in(:,:,11), pcols, lchnk)
    call outfld('FDSC_int11     ',swdown_rad_spec_in(:,:,11), pcols, lchnk)
    call outfld('FUSC_int12     ',swup_rad_spec_in(:,:,12), pcols, lchnk)
    call outfld('FDSC_int12     ',swdown_rad_spec_in(:,:,12), pcols, lchnk)
    call outfld('FUSC_int13     ',swup_rad_spec_in(:,:,13), pcols, lchnk)
    call outfld('FDSC_int13     ',swdown_rad_spec_in(:,:,13), pcols, lchnk)
    call outfld('FUSC_int14     ',swup_rad_spec_in(:,:,14), pcols, lchnk)
    call outfld('FDSC_int14     ',swdown_rad_spec_in(:,:,14), pcols, lchnk)
    call outfld('FUSC_int15     ',swup_rad_spec_in(:,:,15), pcols, lchnk)
    call outfld('FDSC_int15     ',swdown_rad_spec_in(:,:,15), pcols, lchnk)
    call outfld('FUSC_int16     ',swup_rad_spec_in(:,:,16), pcols, lchnk)
    call outfld('FDSC_int16     ',swdown_rad_spec_in(:,:,16), pcols, lchnk)
    call outfld('FUSC_int17     ',swup_rad_spec_in(:,:,17), pcols, lchnk)
    call outfld('FDSC_int17    ',swdown_rad_spec_in(:,:,17), pcols, lchnk)
    call outfld('FUSC_int18     ',swup_rad_spec_in(:,:,18), pcols, lchnk)
    call outfld('FDSC_int18     ',swdown_rad_spec_in(:,:,18), pcols, lchnk)
    call outfld('FUSC_int19     ',swup_rad_spec_in(:,:,19), pcols, lchnk)
    call outfld('FDSC_int19     ',swdown_rad_spec_in(:,:,19), pcols, lchnk)
    call outfld('FUSC_int20     ',swup_rad_spec_in(:,:,20), pcols, lchnk)
    call outfld('FDSC_int20     ',swdown_rad_spec_in(:,:,20), pcols, lchnk)
    call outfld('FUSC_int21     ',swup_rad_spec_in(:,:,21), pcols, lchnk)
    call outfld('FDSC_int21     ',swdown_rad_spec_in(:,:,21), pcols, lchnk)
    call outfld('FUSC_int22     ',swup_rad_spec_in(:,:,22), pcols, lchnk)
    call outfld('FDSC_int22     ',swdown_rad_spec_in(:,:,22), pcols, lchnk)
    call outfld('FUSC_int23     ',swup_rad_spec_in(:,:,23), pcols, lchnk)
    call outfld('FDSC_int23     ',swdown_rad_spec_in(:,:,23), pcols, lchnk)
    call outfld('FUSC_int24     ',swup_rad_spec_in(:,:,24), pcols, lchnk)
    call outfld('FDSC_int24     ',swdown_rad_spec_in(:,:,24), pcols, lchnk)
    call outfld('FUSC_int25     ',swup_rad_spec_in(:,:,25), pcols, lchnk)
    call outfld('FDSC_int25     ',swdown_rad_spec_in(:,:,25), pcols, lchnk)
    call outfld('FUSC_int26     ',swup_rad_spec_in(:,:,26), pcols, lchnk)
    call outfld('FDSC_int26     ',swdown_rad_spec_in(:,:,26), pcols, lchnk)
    call outfld('FUSC_int27     ',swup_rad_spec_in(:,:,27), pcols, lchnk)
    call outfld('FDSC_int27     ',swdown_rad_spec_in(:,:,27), pcols, lchnk)
    call outfld('FUSC_int28     ',swup_rad_spec_in(:,:,28), pcols, lchnk)
    call outfld('FDSC_int28     ',swdown_rad_spec_in(:,:,28), pcols, lchnk)

    call outfld('FUSC_toa_int01     ',swup_rad_spec_in(:,1,1), pcols, lchnk)
    call outfld('FDSC_toa_int01     ',swdown_rad_spec_in(:,1,1), pcols, lchnk)
    call outfld('FUSC_toa_int02     ',swup_rad_spec_in(:,1,2), pcols, lchnk)
    call outfld('FDSC_toa_int02     ',swdown_rad_spec_in(:,1,2), pcols, lchnk)
    call outfld('FUSC_toa_int03     ',swup_rad_spec_in(:,1,3), pcols, lchnk)
    call outfld('FDSC_toa_int03     ',swdown_rad_spec_in(:,1,3), pcols, lchnk)
    call outfld('FUSC_toa_int04     ',swup_rad_spec_in(:,1,4), pcols, lchnk)
    call outfld('FDSC_toa_int04     ',swdown_rad_spec_in(:,1,4), pcols, lchnk)
    call outfld('FUSC_toa_int05     ',swup_rad_spec_in(:,1,5), pcols, lchnk)
    call outfld('FDSC_toa_int05     ',swdown_rad_spec_in(:,1,5), pcols, lchnk)
    call outfld('FUSC_toa_int06     ',swup_rad_spec_in(:,1,6), pcols, lchnk)
    call outfld('FDSC_toa_int06     ',swdown_rad_spec_in(:,1,6), pcols, lchnk)
    call outfld('FUSC_toa_int07     ',swup_rad_spec_in(:,1,7), pcols, lchnk)
    call outfld('FDSC_toa_int07     ',swdown_rad_spec_in(:,1,7), pcols, lchnk)
    call outfld('FUSC_toa_int08     ',swup_rad_spec_in(:,1,8), pcols, lchnk)
    call outfld('FDSC_toa_int08     ',swdown_rad_spec_in(:,1,8), pcols, lchnk)
    call outfld('FUSC_toa_int09     ',swup_rad_spec_in(:,1,9), pcols, lchnk)
    call outfld('FDSC_toa_int09     ',swdown_rad_spec_in(:,1,9), pcols, lchnk)
    call outfld('FUSC_toa_int10     ',swup_rad_spec_in(:,1,10), pcols, lchnk)
    call outfld('FDSC_toa_int10     ',swdown_rad_spec_in(:,1,10), pcols, lchnk)
    call outfld('FUSC_toa_int11     ',swup_rad_spec_in(:,1,11), pcols, lchnk)
    call outfld('FDSC_toa_int11     ',swdown_rad_spec_in(:,1,11), pcols, lchnk)
    call outfld('FUSC_toa_int12     ',swup_rad_spec_in(:,1,12), pcols, lchnk)
    call outfld('FDSC_toa_int12     ',swdown_rad_spec_in(:,1,12), pcols, lchnk)
    call outfld('FUSC_toa_int13     ',swup_rad_spec_in(:,1,13), pcols, lchnk)
    call outfld('FDSC_toa_int13     ',swdown_rad_spec_in(:,1,13), pcols, lchnk)
    call outfld('FUSC_toa_int14     ',swup_rad_spec_in(:,1,14), pcols, lchnk)
    call outfld('FDSC_toa_int14     ',swdown_rad_spec_in(:,1,14), pcols, lchnk)
    call outfld('FUSC_toa_int15     ',swup_rad_spec_in(:,1,15), pcols, lchnk)
    call outfld('FDSC_toa_int15     ',swdown_rad_spec_in(:,1,15), pcols, lchnk)
    call outfld('FUSC_toa_int16     ',swup_rad_spec_in(:,1,16), pcols, lchnk)
    call outfld('FDSC_toa_int16     ',swdown_rad_spec_in(:,1,16), pcols, lchnk)
    call outfld('FUSC_toa_int17     ',swup_rad_spec_in(:,1,17), pcols, lchnk)
    call outfld('FDSC_toa_int17     ',swdown_rad_spec_in(:,1,17), pcols, lchnk)
    call outfld('FUSC_toa_int18     ',swup_rad_spec_in(:,1,18), pcols, lchnk)
    call outfld('FDSC_toa_int18     ',swdown_rad_spec_in(:,1,18), pcols, lchnk)
    call outfld('FUSC_toa_int19     ',swup_rad_spec_in(:,1,19), pcols, lchnk)
    call outfld('FDSC_toa_int19     ',swdown_rad_spec_in(:,1,19), pcols, lchnk)
    call outfld('FUSC_toa_int20     ',swup_rad_spec_in(:,1,20), pcols, lchnk)
    call outfld('FDSC_toa_int20     ',swdown_rad_spec_in(:,1,20), pcols, lchnk)
    call outfld('FUSC_toa_int21     ',swup_rad_spec_in(:,1,21), pcols, lchnk)
    call outfld('FDSC_toa_int21     ',swdown_rad_spec_in(:,1,21), pcols, lchnk)
    call outfld('FUSC_toa_int22     ',swup_rad_spec_in(:,1,22), pcols, lchnk)
    call outfld('FDSC_toa_int22     ',swdown_rad_spec_in(:,1,22), pcols, lchnk)
    call outfld('FUSC_toa_int23     ',swup_rad_spec_in(:,1,23), pcols, lchnk)
    call outfld('FDSC_toa_int23     ',swdown_rad_spec_in(:,1,23), pcols, lchnk)
    call outfld('FUSC_toa_int24     ',swup_rad_spec_in(:,1,24), pcols, lchnk)
    call outfld('FDSC_toa_int24     ',swdown_rad_spec_in(:,1,24), pcols, lchnk)
    call outfld('FUSC_toa_int25     ',swup_rad_spec_in(:,1,25), pcols, lchnk)
    call outfld('FDSC_toa_int25     ',swdown_rad_spec_in(:,1,25), pcols, lchnk)
    call outfld('FUSC_toa_int26     ',swup_rad_spec_in(:,1,26), pcols, lchnk)
    call outfld('FDSC_toa_int26     ',swdown_rad_spec_in(:,1,26), pcols, lchnk)
    call outfld('FUSC_toa_int27     ',swup_rad_spec_in(:,1,27), pcols, lchnk)
    call outfld('FDSC_toa_int27     ',swdown_rad_spec_in(:,1,27), pcols, lchnk)
    call outfld('FUSC_toa_int28     ',swup_rad_spec_in(:,1,28), pcols, lchnk)
    call outfld('FDSC_toa_int28     ',swdown_rad_spec_in(:,1,28), pcols, lchnk)


    ! longwave
    call outfld('FULC_int01     ',lwup_rad_spec_in(:,:,1), pcols, lchnk)
    call outfld('FDLC_int01     ',lwdown_rad_spec_in(:,:,1), pcols, lchnk)
    call outfld('FULC_int02     ',lwup_rad_spec_in(:,:,2), pcols, lchnk)
    call outfld('FDLC_int02     ',lwdown_rad_spec_in(:,:,2), pcols, lchnk)
    call outfld('FULC_int03     ',lwup_rad_spec_in(:,:,3), pcols, lchnk)
    call outfld('FDLC_int03     ',lwdown_rad_spec_in(:,:,3), pcols, lchnk)
    call outfld('FULC_int04     ',lwup_rad_spec_in(:,:,4), pcols, lchnk)
    call outfld('FDLC_int04     ',lwdown_rad_spec_in(:,:,4), pcols, lchnk)
    call outfld('FULC_int05     ',lwup_rad_spec_in(:,:,5), pcols, lchnk)
    call outfld('FDLC_int05     ',lwdown_rad_spec_in(:,:,5), pcols, lchnk)
    call outfld('FULC_int06     ',lwup_rad_spec_in(:,:,6), pcols, lchnk)
    call outfld('FDLC_int06     ',lwdown_rad_spec_in(:,:,6), pcols, lchnk)
    call outfld('FULC_int07     ',lwup_rad_spec_in(:,:,7), pcols, lchnk)
    call outfld('FDLC_int07     ',lwdown_rad_spec_in(:,:,7), pcols, lchnk)
    call outfld('FULC_int08     ',lwup_rad_spec_in(:,:,8), pcols, lchnk)
    call outfld('FDLC_int08     ',lwdown_rad_spec_in(:,:,8), pcols, lchnk)
    call outfld('FULC_int09     ',lwup_rad_spec_in(:,:,9), pcols, lchnk)
    call outfld('FDLC_int09     ',lwdown_rad_spec_in(:,:,9), pcols, lchnk)
    call outfld('FULC_int10     ',lwup_rad_spec_in(:,:,10), pcols, lchnk)
    call outfld('FDLC_int10     ',lwdown_rad_spec_in(:,:,10), pcols, lchnk)
    call outfld('FULC_int11     ',lwup_rad_spec_in(:,:,11), pcols, lchnk)
    call outfld('FDLC_int11     ',lwdown_rad_spec_in(:,:,11), pcols, lchnk)
    call outfld('FULC_int12     ',lwup_rad_spec_in(:,:,12), pcols, lchnk)
    call outfld('FDLC_int12     ',lwdown_rad_spec_in(:,:,12), pcols, lchnk)
    call outfld('FULC_int13     ',lwup_rad_spec_in(:,:,13), pcols, lchnk)
    call outfld('FDLC_int13     ',lwdown_rad_spec_in(:,:,13), pcols, lchnk)
    call outfld('FULC_int14     ',lwup_rad_spec_in(:,:,14), pcols, lchnk)
    call outfld('FDLC_int14     ',lwdown_rad_spec_in(:,:,14), pcols, lchnk)
    call outfld('FULC_int15     ',lwup_rad_spec_in(:,:,15), pcols, lchnk)
    call outfld('FDLC_int15     ',lwdown_rad_spec_in(:,:,15), pcols, lchnk)
    call outfld('FULC_int16     ',lwup_rad_spec_in(:,:,16), pcols, lchnk)
    call outfld('FDLC_int16     ',lwdown_rad_spec_in(:,:,16), pcols, lchnk)
    call outfld('FULC_int17     ',lwup_rad_spec_in(:,:,17), pcols, lchnk)
    call outfld('FDLC_int17     ',lwdown_rad_spec_in(:,:,17), pcols, lchnk)
    call outfld('FULC_int18     ',lwup_rad_spec_in(:,:,18), pcols, lchnk)
    call outfld('FDLC_int18     ',lwdown_rad_spec_in(:,:,18), pcols, lchnk)
    call outfld('FULC_int19     ',lwup_rad_spec_in(:,:,19), pcols, lchnk)
    call outfld('FDLC_int19     ',lwdown_rad_spec_in(:,:,19), pcols, lchnk)
    call outfld('FULC_int20     ',lwup_rad_spec_in(:,:,20), pcols, lchnk)
    call outfld('FDLC_int20     ',lwdown_rad_spec_in(:,:,20), pcols, lchnk)
    call outfld('FULC_int21     ',lwup_rad_spec_in(:,:,21), pcols, lchnk)
    call outfld('FDLC_int21     ',lwdown_rad_spec_in(:,:,21), pcols, lchnk)
    call outfld('FULC_int22     ',lwup_rad_spec_in(:,:,22), pcols, lchnk)
    call outfld('FDLC_int22     ',lwdown_rad_spec_in(:,:,22), pcols, lchnk)
    call outfld('FULC_int23     ',lwup_rad_spec_in(:,:,23), pcols, lchnk)
    call outfld('FDLC_int23     ',lwdown_rad_spec_in(:,:,23), pcols, lchnk)
    call outfld('FULC_int24     ',lwup_rad_spec_in(:,:,24), pcols, lchnk)
    call outfld('FDLC_int24     ',lwdown_rad_spec_in(:,:,24), pcols, lchnk)
    call outfld('FULC_int25     ',lwup_rad_spec_in(:,:,25), pcols, lchnk)
    call outfld('FDLC_int25     ',lwdown_rad_spec_in(:,:,25), pcols, lchnk)
    call outfld('FULC_int26     ',lwup_rad_spec_in(:,:,26), pcols, lchnk)
    call outfld('FDLC_int26     ',lwdown_rad_spec_in(:,:,26), pcols, lchnk)
    call outfld('FULC_int27     ',lwup_rad_spec_in(:,:,27), pcols, lchnk)
    call outfld('FDLC_int27     ',lwdown_rad_spec_in(:,:,27), pcols, lchnk)
    call outfld('FULC_int28     ',lwup_rad_spec_in(:,:,28), pcols, lchnk)
    call outfld('FDLC_int28     ',lwdown_rad_spec_in(:,:,28), pcols, lchnk)

    call outfld('FULC_toa_int01     ',lwup_rad_spec_in(:,1,1), pcols, lchnk)
    call outfld('FDLC_toa_int01     ',lwdown_rad_spec_in(:,1,1), pcols, lchnk)
    call outfld('FULC_toa_int02     ',lwup_rad_spec_in(:,1,2), pcols, lchnk)
    call outfld('FDLC_toa_int02     ',lwdown_rad_spec_in(:,1,2), pcols, lchnk)
    call outfld('FULC_toa_int03     ',lwup_rad_spec_in(:,1,3), pcols, lchnk)
    call outfld('FDLC_toa_int03     ',lwdown_rad_spec_in(:,1,3), pcols, lchnk)
    call outfld('FULC_toa_int04     ',lwup_rad_spec_in(:,1,4), pcols, lchnk)
    call outfld('FDLC_toa_int04     ',lwdown_rad_spec_in(:,1,4), pcols, lchnk)
    call outfld('FULC_toa_int05     ',lwup_rad_spec_in(:,1,5), pcols, lchnk)
    call outfld('FDLC_toa_int05     ',lwdown_rad_spec_in(:,1,5), pcols, lchnk)
    call outfld('FULC_toa_int06     ',lwup_rad_spec_in(:,1,6), pcols, lchnk)
    call outfld('FDLC_toa_int06     ',lwdown_rad_spec_in(:,1,6), pcols, lchnk)
    call outfld('FULC_toa_int07     ',lwup_rad_spec_in(:,1,7), pcols, lchnk)
    call outfld('FDLC_toa_int07     ',lwdown_rad_spec_in(:,1,7), pcols, lchnk)
    call outfld('FULC_toa_int08     ',lwup_rad_spec_in(:,1,8), pcols, lchnk)
    call outfld('FDLC_toa_int08     ',lwdown_rad_spec_in(:,1,8), pcols, lchnk)
    call outfld('FULC_toa_int09     ',lwup_rad_spec_in(:,1,9), pcols, lchnk)
    call outfld('FDLC_toa_int09     ',lwdown_rad_spec_in(:,1,9), pcols, lchnk)
    call outfld('FULC_toa_int10     ',lwup_rad_spec_in(:,1,10), pcols, lchnk)
    call outfld('FDLC_toa_int10     ',lwdown_rad_spec_in(:,1,10), pcols, lchnk)
    call outfld('FULC_toa_int11     ',lwup_rad_spec_in(:,1,11), pcols, lchnk)
    call outfld('FDLC_toa_int11     ',lwdown_rad_spec_in(:,1,11), pcols, lchnk)
    call outfld('FULC_toa_int12     ',lwup_rad_spec_in(:,1,12), pcols, lchnk)
    call outfld('FDLC_toa_int12     ',lwdown_rad_spec_in(:,1,12), pcols, lchnk)
    call outfld('FULC_toa_int13     ',lwup_rad_spec_in(:,1,13), pcols, lchnk)
    call outfld('FDLC_toa_int13     ',lwdown_rad_spec_in(:,1,13), pcols, lchnk)
    call outfld('FULC_toa_int14     ',lwup_rad_spec_in(:,1,14), pcols, lchnk)
    call outfld('FDLC_toa_int14     ',lwdown_rad_spec_in(:,1,14), pcols, lchnk)
    call outfld('FULC_toa_int15     ',lwup_rad_spec_in(:,1,15), pcols, lchnk)
    call outfld('FDLC_toa_int15     ',lwdown_rad_spec_in(:,1,15), pcols, lchnk)
    call outfld('FULC_toa_int16     ',lwup_rad_spec_in(:,1,16), pcols, lchnk)
    call outfld('FDLC_toa_int16     ',lwdown_rad_spec_in(:,1,16), pcols, lchnk)
    call outfld('FULC_toa_int17     ',lwup_rad_spec_in(:,1,17), pcols, lchnk)
    call outfld('FDLC_toa_int17     ',lwdown_rad_spec_in(:,1,17), pcols, lchnk)
    call outfld('FULC_toa_int18     ',lwup_rad_spec_in(:,1,18), pcols, lchnk)
    call outfld('FDLC_toa_int18     ',lwdown_rad_spec_in(:,1,18), pcols, lchnk)
    call outfld('FULC_toa_int19     ',lwup_rad_spec_in(:,1,19), pcols, lchnk)
    call outfld('FDLC_toa_int19     ',lwdown_rad_spec_in(:,1,19), pcols, lchnk)
    call outfld('FULC_toa_int20     ',lwup_rad_spec_in(:,1,20), pcols, lchnk)
    call outfld('FDLC_toa_int20     ',lwdown_rad_spec_in(:,1,20), pcols, lchnk)
    call outfld('FULC_toa_int21     ',lwup_rad_spec_in(:,1,21), pcols, lchnk)
    call outfld('FDLC_toa_int21     ',lwdown_rad_spec_in(:,1,21), pcols, lchnk)
    call outfld('FULC_toa_int22     ',lwup_rad_spec_in(:,1,22), pcols, lchnk)
    call outfld('FDLC_toa_int22     ',lwdown_rad_spec_in(:,1,22), pcols, lchnk)
    call outfld('FULC_toa_int23     ',lwup_rad_spec_in(:,1,23), pcols, lchnk)
    call outfld('FDLC_toa_int23     ',lwdown_rad_spec_in(:,1,23), pcols, lchnk)
    call outfld('FULC_toa_int24     ',lwup_rad_spec_in(:,1,24), pcols, lchnk)
    call outfld('FDLC_toa_int24     ',lwdown_rad_spec_in(:,1,24), pcols, lchnk)
    call outfld('FULC_toa_int25     ',lwup_rad_spec_in(:,1,25), pcols, lchnk)
    call outfld('FDLC_toa_int25     ',lwdown_rad_spec_in(:,1,25), pcols, lchnk)
    call outfld('FULC_toa_int26     ',lwup_rad_spec_in(:,1,26), pcols, lchnk)
    call outfld('FDLC_toa_int26     ',lwdown_rad_spec_in(:,1,26), pcols, lchnk)
    call outfld('FULC_toa_int27     ',lwup_rad_spec_in(:,1,27), pcols, lchnk)
    call outfld('FDLC_toa_int27     ',lwdown_rad_spec_in(:,1,27), pcols, lchnk)
    call outfld('FULC_toa_int28     ',lwup_rad_spec_in(:,1,28), pcols, lchnk)
    call outfld('FDLC_toa_int28     ',lwdown_rad_spec_in(:,1,28), pcols, lchnk)

end subroutine outfld_spectral_flux_clearsky




end module spectral_output
