"""
Created on Sat June 5 21:25:32 2021
@author: Vidya Venkatesan (vidyav1@uci.edu)

Modified by
@author Eric Wolf
@author Claude

Project description: This code is a python version of ice_gcm.pro which calculates the albedo from stellar
spectrum and spectrum of reflectance.
Note: any spectrum file can be used along with any
reflectance spectrum provided the minGrid and maxGrid parameters are changed to reflect the appropriate units.
Units are not important (as long as the wavelength units are the same for each file) for the
final albedo calculations since it is normalized by both the wavelength and the stellar spectrum.

Stellar input — two accepted formats (autodetected by extension):
    ASCII (default): two columns
                         1 - wavelength, ANGSTROM (converted to microns)
                         2 - flux, in any units (normalized for the albedo calc)
                     The leading comment/header block is autodetected: any
                     number of leading lines whose first two whitespace tokens
                     do not parse as floats are skipped. Override with
                     --header-lines N to force a fixed skip count.
    ExoRT n68/n84 NetCDF (*.nc): variables wav_low, wav_high (cm-1 band edges)
                     and solarflux (W/m2 integrated in each band). Band edges
                     are converted to micron band centers; per-band flux is
                     converted to a per-micron flux density so it feeds the
                     same uniform-grid integration as the ASCII path.

    albedofile  = file containing (at least) two columns (as generated by the USGS):
                         1 - wavelength, in microns
                         2 - reflectance at that wavelength (0 - 1)
                         3 - error, if any
"""
#Importing all the libraries
import numpy as np
import scipy.interpolate as ip
import matplotlib.pyplot as plt
import scipy.interpolate as interpol
import argparse
from pathlib import Path
import sys

# input arguments and options
parser = argparse.ArgumentParser()
parser.add_argument('stel'     , type=str,  default=' ',  help='Stellar spectra file name (ASCII 2-column, or ExoRT n68/n84 *.nc)')
parser.add_argument('--stel_dir'     , type=str,   default='/discover/nobackup/etwolf/models/ExoRT/data/solar/raw',  help='Standard directory')
parser.add_argument('--header-lines', type=int, default=None, help='Force this many leading header lines to skip in an ASCII stellar file (default: autodetect)')
parser.add_argument('--snow',        action='store_true', help='use snow albedo file')
parser.add_argument('--blueice',       action='store_true', help='use blue marine ice file')
parser.add_argument('--mixed',        action='store_true', help='use 50/50 mix file')
args = parser.parse_args()


directory = Path(args.stel_dir)
filename = args.stel
stellar_file = directory / filename


#Set number of lines of header information to ignore
alb_nh = 1

#Conversion factor
#wavelengths must be converted to microns
#check header information for given SED
#1.0e-4 angstroms to microns
stel_convert_wavl = 1.0e-4
#stel_convert_wavl = 1.0
alb_convert_wavl = 1.0


def _detect_header_lines(lines):
    """Return the number of leading lines that are NOT a numeric (wavelength, flux)
    data row. A line counts as data once its first two whitespace tokens both
    parse as floats; everything before the first such line is header."""
    for i, line in enumerate(lines):
        toks = line.split()
        if len(toks) >= 2:
            try:
                float(toks[0]); float(toks[1])
                return i
            except ValueError:
                pass
    return len(lines)


def read_stellar_ascii(path, forced_header=None):
    """Read a 2-column ASCII stellar SED. Returns (lamda_microns, flux) lists.
    Header length is autodetected unless forced_header is given."""
    with open(path, 'r') as f:
        lines = f.readlines()
    nh = forced_header if forced_header is not None else _detect_header_lines(lines)
    lamda = []
    flux = []
    for line in lines[nh:]:
        try:
            lamda.append(float(line.split()[0]) * stel_convert_wavl)
            flux.append(float(line.split()[1]))
        except (ValueError, IndexError):
            # Skip lines that cannot be converted to float
            print(f"Skipping line: {line.strip()}")
    return lamda, flux


def read_stellar_netcdf(path):
    """Read an ExoRT n68/n84 NetCDF stellar file. Returns (lamda_microns, flux)
    sorted by increasing wavelength.

    wav_low/wav_high are band edges in cm-1; solarflux is W/m2 integrated in each
    band. We convert each band to a micron band center and a per-micron flux
    density (band flux / band width in microns) so that the downstream uniform-
    grid interpolation + constant-dlamda integration recovers the correct
    band-weighted spectral average."""
    import netCDF4 as nc
    d = nc.Dataset(str(path))
    wav_low = np.asarray(d['wav_low'][:], dtype=float)   # cm-1
    wav_high = np.asarray(d['wav_high'][:], dtype=float)  # cm-1
    solarflux = np.asarray(d['solarflux'][:], dtype=float)  # W/m2 per band
    d.close()

    # cm-1 -> micron:  lambda_um = 1e4 / wavenumber_cm-1
    lam_low = 1.0e4 / wav_high   # high wavenumber -> short wavelength
    lam_high = 1.0e4 / wav_low   # low  wavenumber -> long  wavelength
    lam_center = 0.5 * (lam_low + lam_high)
    band_width_um = lam_high - lam_low
    flux_density = solarflux / band_width_um  # W/m2/micron

    order = np.argsort(lam_center)
    return lam_center[order].tolist(), flux_density[order].tolist()


# Dispatch on file type: NetCDF if .nc extension, else ASCII.
if str(stellar_file).lower().endswith('.nc'):
    lamda, flux = read_stellar_netcdf(stellar_file)
else:
    lamda, flux = read_stellar_ascii(stellar_file, forced_header=args.header_lines)



alb_modes = [args.mixed, args.snow, args.blueice]
true_count = sum(alb_modes)
if true_count != 1:
        print("\nConfiguration Error: Invalid execution mode selected.")
        print(f"You must select **exactly one** of --snow, --blueice, or --mixed.")

        # Optionally show the usage/help message before exiting
        #parser.print_help()

        # Exit the script with a non-zero status code (indicates an error)
        sys.exit(1)

#Reading in the Albedo file for surface
if args.mixed:    albedo_file = "../spectral_albedos/50%Mixture.txt"
if args.snow:  albedo_file = "../spectral_albedos/snow100um.txt"
if args.blueice:     albedo_file = "../spectral_albedos/Bluemarineice.txt"
with open(albedo_file, 'r') as f:
    lines = f.readlines()
    header = lines[0:alb_nh]
    wave = [float(line.split()[0]) * alb_convert_wavl for line in lines[alb_nh:]]
    albedo = [float(line.split()[1]) for line in lines[alb_nh:]]

print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
print("Using stellar spectral file...")
print("  ", stellar_file)
print("Using albedo file...")
print("  ", albedo_file)

#find the minimum and maximum in both stellar and albedo files and match them for interpolation purpose
a = np.min(wave)
b = np.max(wave)
c = np.min(lamda)
d = np.max(lamda)
start_g = max(a,c)
end_g = min(b,d)

# Checking maximum and minimum grid is important else code result is NAN. Default = 2.5, Warm ice 2.3
mingrid = start_g
maxgrid = end_g


#Set up the grid
ngrid = 10000
n = np.arange(10000)
k = maxgrid - mingrid
wavelengthgrid = (mingrid + k * n / (ngrid-1))
dlamda = (np.max(wavelengthgrid)- np.min(wavelengthgrid))/(len(wavelengthgrid)-1)

# Interpolation
#print(len(wavelengthgrid),len(lamda),len(flux))
stellarInterpolate4 = np.interp(wavelengthgrid,lamda,flux)
temp = interpol.CubicSpline(wave,albedo)
albedoInterpolate = temp(wavelengthgrid)

#Normalization
flux4 = stellarInterpolate4/np.max(stellarInterpolate4)

#More calculations for scaling
Snorm = 1360
total_sed4 = sum(stellarInterpolate4*dlamda)
ScaleFac = Snorm/total_sed4
scaledflux4 = total_sed4*ScaleFac
new_total_sed4 = scaledflux4
new_flux4 = stellarInterpolate4*ScaleFac
total_new_flux_4 = sum(new_flux4 * dlamda)

#Setting up cuts between IR and Vis
#cutoff wavelengths in microns
cutoff = 0.76923
ind_v = np.where(wavelengthgrid[:]<cutoff)
ind_i = np.where(wavelengthgrid[:]> cutoff )

print("Using cuttoff wavelength (microns) ...")
print("  ", cutoff)

#use this to calculate bond albedo
ind_w = np.where(wavelengthgrid[:]>0)

#Multiplying reflectance spectrum to normalized stellar specrtrum
albedo_sed_M_v = (albedoInterpolate[ind_v]) * (new_flux4[ind_v]) *dlamda
albedo_sed_M_i = (albedoInterpolate[ind_i]) * (new_flux4[ind_i]) *dlamda
albedo_sed = (albedoInterpolate[ind_w])*(new_flux4[ind_w]) *dlamda

#Calculate the sum
total_albedo_sed_M_v = sum(albedo_sed_M_v)
total_albedo_sed_M_i = sum(albedo_sed_M_i)
total_albedo_sed = sum(albedo_sed)

total_sed_M_v = sum(new_flux4[ind_v]*dlamda)
total_sed_M_i = sum(new_flux4[ind_i]*dlamda)
total_sed = sum(new_flux4[ind_w]*dlamda)

#Calculate albedo for IR, Vis, and bond albedo for a given host star SED
albedo_M_v = total_albedo_sed_M_v/total_sed_M_v
albedo_M_i = total_albedo_sed_M_i/total_sed_M_i
Bond_albedo = total_albedo_sed/total_sed

#Print the numbers
print('Albedo Vis =', albedo_M_v)
print('Albedo IR =', albedo_M_i)
print('Broadband Albedo =', Bond_albedo)
print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
